### ISSUE TITLE
Broken tests (and possibly analyzer) for CA2200

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#1016]
#### Analyzer package
Microsoft.QualityGuidelines.Analyzers

#### Analyzer
CA2200: RethrowToPreserveStackDetailsAnalyzer

The code in test https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.QualityGuidelines.Analyzers/UnitTests/RethrowToPreserveStackDetailsTests.cs#L69 contains several compile errors:

```csharp
01 using System;
02 
03 class Program
04 {
05     void CatchAndRethrowExplicitly()
06     {   
07         try
08         {
09             try
10             {
11                 throw new ArithmeticException();
12             }
13             catch (ArithmeticException e)
14             {
15                 throw;
16             }
17             catch (ArithmeticException)
18                 try
19                 {
20                     throw new ArithmeticException();
21                 }
22                 catch (ArithmeticException i)
23                 {
24                     throw e;
25                 }
26             }
27         }
28         catch (Exception e)
29         {
30             throw;
31         }
32     }
33 }
```

* line 17: CS1514 { expected
* line 24: CS0103 The name 'e' does not exist in the current context
* line 17: CS0160 A previous catch clause already catches all exceptions of this or of a super type ('ArithmeticException')

Fixing any of these errors causes the analyzer under test to start emitting warnings, while the test expects no warnings. Of course the broken code could be intentional, but based on the test name CA2200CSharpTestWithLegalExceptionThrowNested that seems unlikely.

Often it helps to look at [the related VB test](CA2200VisualBasicTestWithLegalExceptionThrowNested). But that one has its own compiler errors, so I'm lost on how to resolve these.

Are only these tests broken, or is the analyzer too?

**Comment by bkoelman** [comment]
@srivatsn I'm having difficulties tracking the author of these tests. Do you know?

**Comment by srivatsn** [comment]
@jmarolf did you originally write this rule?

**Comment by jmarolf** [comment]
>- line 17: CS1514 { expected
- line 24: CS0103 The name 'e' does not exist in the current context
- line 17: CS0160 A previous catch clause already catches all exceptions of this or of a super type ('ArithmeticException')

Well the missing `{` is an error and should be fixed up.  If you fix the other two errors you should get a warning because then you are throwing a caught exception instead of just doing `throw;` to preserve stack details.  The test verifies that we do not issue a warning in the presence of errors. 

The name for this test is bad. It appears I used the term `Legal` to mean that a warning should not be issued, don't know what I was thinking.  Feel free to change to something better.
