### ISSUE TITLE
"Supress Results from Generated code (Managed Only)" does not work as expected with FXCopAnalyzer

### ISSUE THREAD

**Issue by wpanja** [dotnet/roslyn-analyzers#1107]
#### Analyzer package

https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/1.2.0-beta2.

#### Analyzer

Example: GeneratedCodeAttribute Attribute

#### Repro steps

1. VS 2017 RC3, Analyzer version 1.2.0 Beta2
2. \\elements\share\FxCopAnalyzerTests is location of Sample
3. As a consumer of analyzers the above shows a sample where FxCopAnalyzers are being used which contains two typed DataSet declarations. In this case MS Dataset Generator was used
4. Code Analysis During Compilation is enabled with "Supress Results from Generated code (Managed Only)" Checked

#### Expected behavior

The warnings we see; should be is expected to be excluded after we select the option to Supress them from analysis,

In case of standard MS provided generators like typed dataset generator, winform designer, etc. end users cannot change generators to provide good code (from analyzers POV)

#### Actual behavior

We see this;

![111](https://cloud.githubusercontent.com/assets/22373988/22643547/fff1067c-ec84-11e6-9d47-d49aa433c8d4.jpg)

@mavasani

**Comment by mavasani** [comment]
The issue here is with [SerializationRulesDiagnosticAnalyzer](https://github.com/dotnet/roslyn-analyzers/blob/569bd373a4831d3035597197e02980b57602a7f2/src/Desktop.Analyzers/Core/SerializationDiagnosticAnalyzer.cs) - it should register separate actions for field symbols, not directly operate on fields of named types, as named type might have partial definitions, and the fields defined on a generated partial definition shouldn't be analyzed.

**Comment by mavasani** [comment]
Actually, this doesn't repro on the latest VS bits with our latest analyzer bits. Closing this as no repro...
