### ISSUE TITLE
Justification for RS0023: <class> is exported with MEFv2 and hence must be marked as Shared

### ISSUE THREAD

**Issue by jherby2k** [dotnet/roslyn-analyzers#1436]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version [2.6.0-beta1]

#### Analyzer

RS0023: <class> is exported with MEFv2 and hence must be marked as Shared

#### Repro steps

1. Create a class using MEFv2, export it but don't add the [Shared] attribute

#### Expected behavior

I don't want to create shared parts, I want per-instance parts.

#### Actual behavior

Works as expected without [Shared], and I can't find any explanation on the internet for why this analyzer exists.

**Comment by mavasani** [comment]
Seems like the analyzer was originally written for Roslyn.sln by @jasonmalinowski and then moved to [Microsoft.NetCore.Analyzers](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Core/Composition/PartsExportedWithMEFv2MustBeMarkedAsShared.cs). [DoNotMixAttributesFromDifferentVersionsOfMEF](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Core/Composition/DoNotMixAttributesFromDifferentVersionsOfMEF.cs) was handled similarly.

@jasonmalinowski, do you think these two analyzers are useful outside of our solution(s), and if so can you give a more detailed description for us to add? If you think otherwise, we can move these back into Roslyn.sln specific analyzer package, so FxCopAnalyzers package will no longer have these analyzers.

**Comment by mavasani** [comment]
@jherby2k Thanks for the report. For now, you can suppress these rules to avoid noise in your project.

**Comment by jasonmalinowski** [comment]
Correct, this was very specific to Roslyn. Ditto for DoNotMixAttributesFromDifferentVersionsOfMEF.

**Comment by jasonmalinowski** [comment]
@mavasani Is there a project that is once again Roslyn-specific?

**Comment by mavasani** [comment]
@jasonmalinowski Yes, we [Roslyn.Diagnostics.Analyzers](https://github.com/dotnet/roslyn-analyzers/tree/master/src/Roslyn.Diagnostics.Analyzers/Core), which are not included in FxCopAnalyzers package.

**Comment by mavasani** [comment]
I will move these analyzer back to Roslyn.Diagnostics.Analyzers project.
