### ISSUE TITLE
Do not run Async002 codefix when renaming will cause a conflict

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1485]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

AsyncMethodsShouldEndInAsync

#### Description

The codefix should not kick in (but the analyzer should still fire) when appending `Async` to the method name will result in a conflict with an existing method. e.g.

```cs
// Warning, but no codefix
private static async Task<int> Math(int, int);

private static async Task<int> MathAsync(int, int);
```

I'm not sure what the best way to implement this is. The old analyzer simply iterated through each token in the syntax tree and check if it was an identifier matching `MathAsync`, but I'm not sure that's the best way to do that. Should I use `SemanticModel.LookupSymbols()` for this? I noticed there's a dedicated [ConflictResolver](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Rename/ConflictEngine/ConflictResolver.cs,09bdad5ed4883671) type in Roslyn, any way I can make use of that?

**Comment by mavasani** [comment]
@jamesqo You should simply add a [RenameAnnotation](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeRefactorings/ExtractMethod/AbstractExtractMethodCodeRefactoringProvider.cs,88) to the method name identifier, so that your code fix will bring up a rename session, show the conflicts and let user handle it appropriately.

**Comment by mavasani** [comment]
Async usage analyzers are no longer supported in this repo.
