### ISSUE TITLE
"Avoid Async Void" Analyzer

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1576]
feedback from [link](https://developercommunity.visualstudio.com/content/problem/146858/c-async-danger.html)

If an interface has a void method, then a caller should reasonably expect any exception to be caught in a try/catch block. This is not true if the implementation of the interface specifies "async" as an exception can be unhandled on the thread pool. This can crash the hosting process. Please prevent the async keyword being used by implementers of a void method on an interface when the void method does not also declare the async keyword

**Comment by sharwell** [comment]
:memo: This is implemented in DotNetAnalyzers/AsyncUsageAnalyzers.

**Comment by mavasani** [comment]
We are not going to implement async analyzers in this repo. Recommendation is to use VS threading analyzers or AsyncUsageAnalyzers

**Comment by drewnoakes** [comment]
Implemented in vs-threading as [VSTHRD100](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD100.md).

**Comment by cremor** [comment]
> We are not going to implement async analyzers in this repo.

Is this still true? Do you still recommend using Microsoft.VisualStudio.Threading.Analyzers in current .NET projects?

I'm asking because there are a few async analyzers here which seem to have been ported from Microsoft.VisualStudio.Threading.Analyzers. And those that have been ported seem to be even improved. For example, if I add  Microsoft.VisualStudio.Threading.Analyzers to my project now (just to get the `async void` analyzer) I get wrong warnings for EF Core `DbContext.AddRange` methods. Those wrong warnings have been fixed here in #6858, but it looks like they were not fixed in  Microsoft.VisualStudio.Threading.Analyzers.

**Comment by sharwell** [comment]
@cremor I believe it is still generally true. There may be one-off exceptions; for those you can disable the analyzer which is providing duplicate behavior.
