### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.2-beta1\rulesets\AllRulesDefault.ruleset is corrupt

### ISSUE THREAD

**Issue by bichuga** [dotnet/roslyn-analyzers#1745]
When using AllRulesDefault, I get warning message:

warnings in directory e:\enlistments\bothellgito365\sources\dev\official\src\signing\signingjsonexporter
e:\enlistments\bothellgito365\sources\dev\official\src\signing\signingjsonexporter\ca0064 : warning No analysis was performed because the specified rule set could not be loaded or did not contain any managed code analysis rules.

There are two sets of rules with nothing enabled which I believe is causing the issue

**Comment by mavasani** [comment]
This ruleset is not meant for Managed Binary Analysis (which is legacy FxCop). Do you see diagnostics when you run FxCop analyzers? I believe there is also a bug in ruleset editor not correctly displaying enabled rules when enabled via ruleset includes (which this ruleset does). Let me try to repro that and file a separate bug.

**Comment by bichuga** [comment]
I'm not sure of the answer to your question. When I save the ruleset with everything checked from VS, it labels it as 
`<Rules AnalyzerId="Microsoft.Analyzers.ManagedCodeAnalysis" RuleNamespace="Microsoft.Rules.Managed">

**Comment by mavasani** [comment]
@bichuga Updating my project to reference the AllRulesDefault.ruleset does have expected behavior:

![image](https://user-images.githubusercontent.com/10605811/43736964-80d5cce4-9974-11e8-9de0-31498a25f3ab.png)

Note: Managed Binary Analysis is for legacy/binary FxCop rules, which are not enabled by this ruleset. The rest of the code quality/netcore/netframework rules are enabled by this ruleset:

![image](https://user-images.githubusercontent.com/10605811/43737008-ad20bb6a-9974-11e8-9883-40b9411c5c7e.png)

Same holds true for AllRulesEnabled.ruleset:

![image](https://user-images.githubusercontent.com/10605811/43737092-e48bf70e-9974-11e8-8b28-5330f83e284b.png)
