### ISSUE TITLE
Duplicated codes

### ISSUE THREAD

**Issue by TrymBeast** [dotnet/roslyn-analyzers#1774]
Hello, while reviewing the rules to use where I work I noticed that there are two duplicated codes (CA5350 and CA5351).
I would expect that rule codes are unique.

Here are the details of this rules:

#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.1

#### Diagnostic ID

CA5350: Do not use insecure cryptographic algorithm SHA1.
CA5351: Do not use insecure cryptographic algorithm MD5.
[CA5350: Do Not Use Weak Cryptographic Algorithms](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca5350-do-not-use-weak-cryptographic-algorithms)
[CA5351: Do Not Use Broken Cryptographic Algorithms](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca5351-do-not-use-broken-cryptographic-algorithms)

**Comment by mavasani** [comment]
@dotpaul @qinxgit I see we have different implementations for these rules in NetCore.Analyzers and NetFramework.Analyzers, possibly because the same rule works on different set of APIs. Will it be possible to combine the rule implementations into NetCore.Analyzers so both NetCore/NetFramework projects get the analyzer, but the rule implementation can have parts specific to netcore and netframework.

**Comment by 333fred** [comment]
I'm not sure that this belongs in `CodeQuality`. It should go in `NetCore`, so that both Framework and Core get the rule (assuming I have that correct @mavasani?)

**Comment by dotpaul** [comment]
Oh, got it.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/1793
