### ISSUE TITLE
"CA2213: Disposable fields should be disposed" doesn't understand CPS (project-system) constructs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#1796]
#### Diagnostic ID

CA2213

#### Repro steps

We turned this rule off because it fires every type that derives from OnceInitializedOnceDisposed/OnceInitializedOnceDisposedAsync which is used heavily through the project-system.

**Comment by davkean** [comment]
Here's the change where we removed the suppressions and turned off the rule: https://github.com/dotnet/project-system/pull/3926.

**Comment by sharwell** [comment]
My general observation with this rule is it's only used for compatibility purposes for people switching from legacy FxCop to FxCop Analyzers. Ongoing development will need a whole new rule, and so far that rule hasn't been defined.

A primary characteristic of the new rule is it should be straightforward for a developer writing *new* code to write `IDisposable` objects with all of the following met:

1. The `IDisposable` objects are disposed at a clear point in program execution after they are no longer in use
2. No suppressions for the new rule are required
3. A set of rules exists which can be followed by a developer to achieve the previous two points, which could be considered guidance for working with the rule

**Comment by mavasani** [comment]
We should still fix this bug.

**Comment by mavasani** [comment]
Note the rule understands lot of Dispose method signatures, and we should enhance it to understand DisposeAsync as a Dispose signature. I will fix this next week.

**Comment by mavasani** [comment]
The underlying issue has been fixed with https://github.com/dotnet/roslyn-analyzers/pull/1968 - we now understand the `DisposeAsync` and `DisposeCoreAsync` signatures. However, note that you might still see false positives if the dispose is done within a helper method called within these methods, i.e. requires https://github.com/dotnet/roslyn-analyzers/issues/1594 to do interprocedural analysis. We will implement this feature in features/dataflow branch, so the 2.9.XXX should not have false positives from that scenario.
