### ISSUE TITLE
"protected internal" is incorectly detected as "Accessibility.ProtectedOrInternal" instead of "ProtectedAndInternal".

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn-analyzers#1807]
#### Analyzer package

Example: [Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp)

#### Package Version

1.2.1

#### Diagnostic ID

A new one currently in a GitHub pull request here: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/2781

#### Repro steps

Try this code in this pull request to StyleCop.Analyzers: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/2781

#### Expected behavior

For the code in the pull request to work as expected.

#### Actual behavior

The single test that tests ``protected internal`` fails.

**Comment by sharwell** [comment]
This is the expected behavior. `protected internal` allows access to everything that would have access for `protected` and also allows access to everything that has access for `internal`, so it works like `(protected || internal)`. The `private protected` modifier is the one that maps to `ProtectedAndInternal`.
