### ISSUE TITLE
CA1812 warnings go away when navigating to the document.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#1831]
Repro steps:

```cs
namespace RoslynSandbox
{
    using NUnit.Framework;

    internal class Tests
    {
        [Test]
        public void SomeTest()
        {
        }
    }
}
```

1. Use ^
2. Close all documents.
3. Rebuild.
4. Click on the `CA1812` warning in the error list to navigate to the document.
5. The warning goes away after a couple of seconds.

**Comment by mavasani** [comment]
This seems like an issue with the error list/IDE diagnostic service, not the analyzer itself - likely related to the fact that CA1812 is a compilation end analyzer. I feel this might be fixed with https://github.com/dotnet/roslyn/pull/27094, which will be available in Dev16 Preview2 (not yet released). If it still repros in that release, kindly file a bug in roslyn repo for the same.
