### ISSUE TITLE
Remove duplicated types

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn-analyzers#192]
The AsyncPackage has a number of types that derive from `CodeAction`. These are identical, except for minor differences in the implementation of the `EquivalenceKey` property.

These types should be replaced with a single type that takes the value of the `EquivalenceKey` as a constructor parameter.

**Comment by sharwell** [comment]
Is there any reason to not just use `CodeAction.Create`?

**Comment by srivatsn** [comment]
The reason we create separate types here is because we use the type name for telemetry purposes and CodeAction.Create would just have the same type name for different fixers. Using type name for telemetry is in itself quite odd and we need a different mechanism for that. We need to create an issue on dotnet\roslyn for such a mechanism and once we have that get rid of these types.

**Comment by srivatsn** [comment]
Blocked by https://github.com/dotnet/roslyn/issues/4919

**Comment by mavasani** [comment]
Stale issue...
