### ISSUE TITLE
CA2007 doesn't seem to make sense in an async void method

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn-analyzers#1953]
CA2007, [DoNotDirectlyAwaitATask](https://github.com/mavasani/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs), does not permit directly awaiting a task.

Adding `.ConfigureAwait(false)` makes little sense in an `async void` method, where we want any exception to be thrown on the original synchronization context, e.g. in a WPF app the Dispatcher should get a chance to handle the exception.

I find that adding `.ConfigureAwait(true)` is useless noise.

Any chance we could turn down this analyzer to ignore `await` operations that occur inside an `async void` method?

**Comment by mavasani** [comment]
Your suggestion seems to be a reasonable default for this rule. In future, we can consider adding an `.editorconfig` option for users to override this default, in case we get user requests for the same.

**Comment by sharwell** [comment]
I don't agree with `async void` being special in this case. I could be swayed, but only on the basis that `async void` is always outright banned (without exception) in projects I work on so I'll never have to deal with this situation.

/cc @AArnott as well

**Comment by AArnott** [comment]
I second @sharwell's take. An `async void` method in general is not guaranteed to be invoked on the UI thread, nor for there to be an applicable `Dispatcher`, nor that that dispatcher will do anything besides crash the process (as is the default behavior) anyway. So to blindly set any policy based on the assumption that `async void` methods meet all those requirements seems like it's targeting a rather small subset of customers.

But as `async void` should be avoided anyway [as a general rule](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD100.md), and as @sharwell mentioned I prefer *not* specifying `.ConfigureAwait(bool)` everywhere ([more on that](https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md#should-i-await-a-task-with-configureawaitfalse)), I have CA2007 turned off anyway. I use [VSTHRD111](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD111.md) when I need to require `ConfigureAwait` because the code fixes offered for it can add *either* `true` or `false` arguments to the suffix. I believe CA2007 only offers `.ConfigureAwait(false)` (for some reason).

**Comment by AArnott** [comment]
I just filed https://github.com/dotnet/roslyn-analyzers/issues/1962 to add `.ConfigureAwait(true)` to CA2007, FYI.

**Comment by sharwell** [comment]
@AArnott thank you, your reply is much better than mine

**Comment by mavasani** [comment]
Thanks @sharwell @AArnott. My takeaways:

1. Update https://github.com/dotnet/roslyn-analyzers/pull/1958 so filtering out async void methods is not the default analyzer implementation, but can be configured via an editorconfig option.
2. Address https://github.com/dotnet/roslyn-analyzers/issues/1962 so users can make an explicit decision on ConfigureAwait and also suppress CA2007 more easily.

**Comment by mavasani** [comment]
This is now configurable: https://github.com/dotnet/roslyn-analyzers/pull/1958/files#diff-1b5cdc4937a8cdfc79545945ad6c0783R69. Default behavior of the analyzer is unchanged.
