### ISSUE TITLE
Need a way to exclude specify file during analyze

### ISSUE THREAD

**Issue by watsonsong** [dotnet/roslyn-analyzers#2140]
Is there any way to exclude a specify file in csproj or Directory.Build.props when using a roslyn-analyzers.

**Comment by mavasani** [comment]
This issue is not related to analyzers from this repo, but analyzers in general. You can try the approach mentioned in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2886. Once .editorconfig support is added to C#/VB compilers, you should be able to specify diagnostic suppressions at folder level by adding an .editorconfig in the folder to skip reporting analyzer diagnostics.

**Comment by mavasani** [comment]
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/2456. Recommendation is to use .editorconfig files to configure rule execution at document level.
