### ISSUE TITLE
CA1309: Use ordinal stringcomparison is not .NET Core specific

### ISSUE THREAD

**Issue by Andrew-Webb** [dotnet/roslyn-analyzers#2169]
This rule is in `Microsoft.NetCore.Analyzers`, but since it isn't specific to .NET Core, it should be elsewhere... e.g. `Microsoft.CodeQuality.Analyzers`.

Ref: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.md#ca1309-use-ordinal-stringcomparison

**Comment by mavasani** [comment]
This is by design.

CodeQuality analyzers contains generic code improvement rules, while NetCore analyzers and NetFramework analyzers contains API usage rules. If the API is present in Netstandard/Netcore then the rule goes in NetCore analyzers, and if API is specific to NetFramework the rule goes there. Netcore and NetFramework Analyzers are written in a way that they check upfront if the corresponding API is present in the compilation, and bail out if not. So the client only needs to install FxCopAnalyzers package (which includes all 3 above mentioned packages) and only the appropriate set of analyzers will execute based on target framework.

**Comment by Andrew-Webb** [comment]
> So the client only needs to install FxCopAnalyzers package (which includes all 3 above mentioned packages) and only the appropriate set of analyzers will execute based on target framework.

Aha!  This is the piece of information I wished I'd known about from the start!  I wasn't sure what to install, and so chose `Microsoft.CodeQuality.Analyzers`.

But you're suggesting that, if unsure, people should probably start with `/Microsoft.CodeAnalysis.FxCopAnalyzers` and get everything.  That is what I shall now do.

Perhaps this could be made more obvious on the front page of the repo.
