### ISSUE TITLE
CA1062: False positive when unvalidated parameter is used by a function 

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/roslyn-analyzers#2275]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Package Version

2.9.1

#### Diagnostic ID

CA1062

#### Repro steps

It incorrectly flags sqlParameterName as needing a parameter check for null. In this example, null is permissible both for SqlParameterName and the Utilities.ToClrName function.

        protected ParameterMetadata(string sqlParameterName, string sqlVariableName, string typeName, object dbType)
        {
            TypeName = typeName;
            SqlParameterName = sqlParameterName;
            ClrName = Utilities.ToClrName(sqlParameterName); <------
            SqlVariableName = sqlVariableName;
            DbType = dbType;
        }

**Comment by mavasani** [comment]
Can you please provide a minimal compilable repro, especially the code for ToClrName function?

**Comment by Grauenwolf** [comment]
I don't have a minimum repro at this time.

        public static string ToClrName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return null;

            string result = name;
            foreach (char c in s_InvalidCharacters)
            {
                result = result.Replace(c.ToString(CultureInfo.InvariantCulture), "");
            }

            if (!char.IsLetter(result[0]) && result[0] != '_')
                result = "_" + result;

            return result;
        }

The overall project is: https://github.com/docevaad/Chain

**Comment by mavasani** [comment]
Needs adding logic to PointsToAnalysis to ensure non-null location on path where `string.IsNullOrXXX` is false.

**Comment by mavasani** [comment]
> Needs adding logic to PointsToAnalysis to ensure non-null location on path where string.IsNullOrXXX is false.

I have a [PR](https://github.com/dotnet/roslyn-analyzers/pull/2345/) for fixing this issue, but it did not require this change. We already had this check [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs#L265). The false positive was due to us incorrectly identifying tracked parameters for interprocedural analysis case, which should be fixed with https://github.com/dotnet/roslyn-analyzers/pull/2345/files#diff-d17d5dddb71f933144e280de5b7fde88R62

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/2345
