### ISSUE TITLE
VS Mac build fails after adding FxCopAnalyzer package

### ISSUE THREAD

**Issue by andreypudov** [dotnet/roslyn-analyzers#2289]
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v2.9.1

#### Diagnostic ID

CSC : error CA9999: Version mismatch between the analyzer package '2.9.0' and Microsoft.CodeAnalysis '2.8.0.0'.
Certain analyzers in this package will not run until the version mismatch is fixed.
Refer to https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2017#fxcopanalyzers-package-versions to install the correct analyzer version.

#### Repro steps

1. Create .NET  Core class library project (using Visual Studio for Mac 8.0.1)
2 Add Microsoft.CodeAnalysis.FxCopAnalyzers package as a dependency
3. Build the project

#### Actual behavior

Build fails

**Comment by mavasani** [comment]
I believe this is by design. Your underlying compiler version is 2.8.x, but the 2.9.x FxCop analyzer package requires the compiler version to be at least 2.9.0. I would recommend either downgrading your analyzer package reference to 2.6.3 OR upgrading the compiler version to 2.9.0 or later (you can do so by referencing [this](https://www.nuget.org/packages/Microsoft.NETCore.Compilers/3.1.0-beta1-final) NuGet package)
