### ISSUE TITLE
CA2213 has high impact on project compile time

### ISSUE THREAD

**Issue by appel1** [dotnet/roslyn-analyzers#2319]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

2.9.1

#### Diagnostic ID

CA2213

#### Repro steps

Enable CA2213 on a fairly big project
Compile solution using msbuild from a Developer Command Prompt for VS 2019 (or 2017)

#### Expected behavior
A small increase in compile time, or at least not doubling it. 

#### Actual behavior
Almost doubles compile time.

![DisposableFieldsShouldBeDisposedImpact](https://user-images.githubusercontent.com/973314/55984422-b3f04680-5c9d-11e9-8969-8234a64efa15.png)

This is from a profiling session compiling one of our solutions with a couple of fairly big projects. While DisposableFieldsShouldBeDisposedImpact runs on a single core almost nothing else happens and it takes up almost half of the total time. The same difference can be observed with the rule on and off without a profiler attached. 

Time with CA2213 enabled: Time Elapsed 00:04:06.17
Time without: Time Elapsed 00:02:11.37

**Comment by mavasani** [comment]
Can you please provide a repro project? Also can you try disabling interprocedural analysis: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#dataflow-analysis.

**Comment by appel1** [comment]
With interprocedural analysis disabled it takes about the same time to build with and without CA2213. 

Unfortunately I can't share the project.

**Comment by mavasani** [comment]
Great, I will tweak the default dalaflow analysis configuration to make it optimal. I will share a myget drop with you next week to verify if that resolves your issue. Thanks!

**Comment by gpetrou** [comment]
We have the same problem.
@mavasani are you planning to release a new 2.9.x version that includes this fix?

**Comment by mavasani** [comment]
@gpetrou Yes, we are planning to release a 2.9.3 build very soon. Just waiting for a bucket of security analyzers to be checked in. Meanwhile, we might push a 2.9.3-beta1 build on nuget.org as there have been quite a few fixes post 2.9.2 which have had more then one customer report.

Also, @appel1 @gpetrou would you be able to verify if the latest myget package which includes the fix for this issue addresses your perf concern: https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.3-beta1.19257.1+c5bf4e0d

**Comment by gpetrou** [comment]
Hmm, the issue still occurs with 2.9.3-beta1.19257.1+c5bf4e0d
Unfortunately, this is a large commercial solution that I cannot share.
Is there some other information I could provide to you to help isolate the issue?

**Comment by gpetrou** [comment]
As with 2.9.2, if I disable interprocedural analysis, it works.

**Comment by mavasani** [comment]
@gpetrou Can you try https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.3-beta1.19264.2+53b6de0b? You don’t need any configuration for it. Thanks again!

**Comment by mavasani** [comment]
@gpetrou - were you able to give the new package a try?

We are planning to release version 2.9.3 of the package, but want to make sure that the issue you have reported is fixed by default in the package (does not require any nowarn or editorconfig setting for interprocedural analysis).

Thanks again!

**Comment by JeremyMorton** [comment]
Yes, I just tried this, and it seems to have fixed my issue.

**Comment by mavasani** [comment]
Awesome, thank you so much @JeremyMorton!
