### ISSUE TITLE
 [loc][Query][roslyn-analyzers] Localizability of "TestExportsShouldNotBeDiscoverableDescription" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2454]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Test exports should not be discoverable

File Name:
Roslyn.Diagnostics.Analyzers\Core\xlf\RoslynDiagnosticsAnalyzersResources.xlf

==========================================
Query:
Please explain the meaning of "Test exports"?

**Comment by mavasani** [comment]
Tagging @sharwell

**Comment by sharwell** [comment]
MEF exports defined in test code. These are typically shim implementations of a service used by one or more tests. Since the export doesn't behave the same way as the production code part, it should only impact tests that specifically request it. MEF achieves this using Partnot discoverable attribute.

**Comment by PDostalek** [comment]
Thanks
