### ISSUE TITLE
Analyzer Request: Property self assignment protection

### ISSUE THREAD

**Issue by mclayton7** [dotnet/roslyn-analyzers#2496]
I'd like to contribute an analyzer that detects self assignment of properties in classes, where constructor arguments are probably meant to be used instead.

```
public class ExampleClass
{
    private string MyProperty { get; set; }

    public ExampleClass(string myProperty)
    {
        MyProperty = MyProperty;
    }
}
```
There's already an example implementation on Stack Overflow (and an explanation on why the compiler allows self assignment with properties): https://stackoverflow.com/questions/35632991/compile-time-detection-of-accidentally-assign-a-c-sharp-property-to-itself

Questions.
- Would you guys welcome a PR for this this?
- If so, which branch should I base a PR on?

Thanks,
Mac

**Comment by mavasani** [comment]
@mclayton7 Thanks, that seems a reasonable analyzer to implement and contribute to this repo (probably under Microsoft.CodeQuality.Analyzers.

I took a quick look at the implementation you cited in stackoverflow, and I would recommend you instead write an IOperation analyzer instead of a syntax node analyzer, which would have better performance characteristics. You would need to register an operation action for [OperationKind.SimpleAssignment](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/OperationKind.cs,104) and then check that the [Target](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IAssignmentOperation.cs,22) and [Value](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IAssignmentOperation.cs,26) both are [IPropertyReferenceOperation](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IPropertyReferenceOperation.cs,19) referencing the same property symbol and whose [Instance](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IMemberReferenceOperation.cs,22) is an [IInstanceReferenceOperation](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IInstanceReferenceExpression.cs,19) whose ReferenceKind is [InstanceReferenceKind.ContainingTypeInstance](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/InstanceReferenceKind.cs,14)

**Comment by mavasani** [comment]
> If so, which branch should I base a PR on?

Please target your PR against master branch.

**Comment by mclayton7** [comment]
@mavasani when you get a chance, could you look at my PR and help get a number assigned to the analyzer? Thanks!

**Comment by mavasani** [comment]
This has been implemented.
