### ISSUE TITLE
Package localized satellite resource assemblies in analyzer NuGet packages

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2577]
Seems like we are producing satellite resource assemblies during build, but not including them in the NuGet package.

![NonLocalizedResources](https://user-images.githubusercontent.com/10605811/59393277-bc154280-8d2f-11e9-9b59-e9b2f984c98e.png)

@tmat @genlu - is there an easy way to specify this in arcade? Or would I need to explicitly fix the build scripts in the repo?

**Comment by tmat** [comment]
Aren't we using custom nuspec generator for analyzer packages? That will need to be updated to include the resource assemblies. 

Perhaps we should also consider removing the custom nusepc generation and build the packages using standard NuGet targets like we now do in Roslyn CodeStyle projects:
https://github.com/dotnet/roslyn/blob/master/src/CodeStyle/CSharp/CodeFixes/Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes.csproj#L20

**Comment by tmat** [comment]
Now that I'm looking at the Roslyn CodeStyle projects, they can also use some cleanup.

Since analyzers do not multi-target we don't need to use [`TfmSpecificPackageFile`](https://github.com/dotnet/roslyn/blob/master/src/CodeStyle/CSharp/CodeFixes/Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes.csproj#L34) item group, and instead just set `<None Include="..." Pack="true"/>`
