### ISSUE TITLE
Let's list added/updated/removed rules in release notes

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#2601]
~~Let's https://keepachangelog.com~~

Let's put info about rule changes in the release notes

**Comment by dotpaul** [comment]
I'm thinking of having a single CHANGELOG.md in src/Microsoft.CodeAnalysis.FxCopAnalyzers, covering all its dependent packages.

----

Like keepachangelog.com suggests, each nuget.org release (prerelease, release, and always at the top, "unreleased" for changes not yet shipped) can have sections for (assuming there are relevant rules / general fixes):
## Added
## Changed
## Removed

----

It might also be useful to further subcategorize by the rule categories, to avoid a wall of text when shipping lots of rules, e.g.:

## Added
### Design rules
- [CAxxxx: Avoid bad patterns](https://docs.microsoft.com/) -- Rule's description or message
### Security rules
- [CAyyyy: Don't write insecure code](https://docs.microsoft.com/)  -- Rule's description or message

----

And always add help links everywhere, even if the rule previously shipped without one.

If we want to get fancy, we can automate some parts like generating an entry for a newly added rule, but we shouldn't sacrifice human readability for easier automation.  For example if there are multiple fixes a single rule in a release, we should only have one line IMO.

**Comment by dotpaul** [comment]
Tagging @mavasani @sharwell @genlu @jinujoseph @vatsalyaagrawal for comments

**Comment by sharwell** [comment]
I've been opposed to keeping changelog files in Git repositories since I started using Git. The changelog for commit A is never in commit A, but rather in some unknown later commit B, and there is no clear link from A to B.

GitHub already keeps a changelog [here](https://github.com/dotnet/roslyn-analyzers/pulls). We just need to start assigning things to the correct milestones on merge.

I'm a big fan of the Releases page on GitHub for release notes. However, producing the release notes for a particular release is a frustrating amount of work. Current automation (e.g. the tool used by @onovotny for [AppInsights.WindowsDesktop](https://github.com/onovotny/AppInsights.WindowsDesktop/releases)) does a poor job of producing a usable release notes page. I'd love to see a tool that combines two things to produce the framework for the release notes:

1. A code analysis tool that produces a summary table for code analysis rules in a particular release
2. A command line tool that interacts with the GitHub API to produce a list of participants in the release (issues filed, code reviews, commented on issues and/or pull requests assigned to the release milestone)

**Comment by dotpaul** [comment]
By "changelog", I was thinking more along the lines of a history of release notes.  I don't think individual commits are useful for communicating to users what's changed, either.  Using GitHub's release page sounds good to me.

One approach for automating a summary of added and removed rules is to have the GenerateAnalyzerRulesets tool also generate release notes (at least the added / removed rules portion).

For a summary of updated rules, I was thinking of something like:
- CA1062: Validate arguments of public methods -- Fixed several false positive cases

(Dunno if that's the level of detail people think is appropriate.  For myself as a user, I don't think I'd find all the PRs useful, but maybe there are users who really would like that.)

...which wouldn't be easily automated, given that it's just a summary and there could be multiple issues and PRs involved.  In any case, I'm sure there'll always be parts of the release notes that someone manually writes, so I think we should have a "scratchpad" .md for the next release notes.  Hopefully that wouldn't end up being a frustrating amount of work to maintain.

Also, really good point about having a list of participants.

**Comment by sharwell** [comment]
> I was thinking more along the lines of a history of release notes.

This is exactly what the [Releases](https://github.com/antlr/antlr4/releases) page is.

**Comment by dotpaul** [comment]
Talking with @sharwell over IM, we can use a draft GitHub release instead of a "scratchpad" file in the repo.  So we should update the draft release notes as we merge fixes / behavior changes.  I've hijacked one of Sam's test drafts for v2.9.4: https://github.com/dotnet/roslyn-analyzers/releases/tag/untagged-29b3a83f9c213da98b79

I'll hack something up to generate notes on new / removed rules between two versions of analyzer binaries.

**Comment by dotpaul** [comment]
Updated the v2.9.x releases at https://github.com/dotnet/roslyn-analyzers/releases
