### ISSUE TITLE
PublicApiAnalyzer should support removing methods in a nicer way.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#2662]
Scenario:
Previous release had method `C.M()` and it is in `PublicAPI.Shipped.txt`
Then the method is removed. Here it would be nice to be able to add for example `- C.M()` to `PublicAPI.Unshipped.txt` so that we don't get the `RS0017` warning.

This is with my current workflow of updating shipped on releasing. It is nice to only do it once so that it there is a trivial diff for release notes and spotting accidental breaking changes.

Maybe there is a better workflow?

**Comment by Evangelink** [comment]
Hi @JohanLarsson,

Out of curiosity, isn't this test 

https://github.com/dotnet/roslyn-analyzers/blob/28ae0e5cb2115d67ea823add02f286cc3a1d0800/src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs#L518-L543

covering exactly the scenario you are describing? Except for the prefix which is `*REMOVED*` instead of `-`.

cc @mavasani

**Comment by JohanLarsson** [comment]
Maybe it is already fixed, I can't say if I have seen it recently. Removing members is somewhat rare.

**Comment by JohanLarsson** [comment]
I'm closing this as it might be fixed. Can always reopen later if I see it on current version
