### ISSUE TITLE
Microsoft.NetCore.Analyzers.Security.DoNotHardCodeEncryptionKey throws System.NotSupportedException

### ISSUE THREAD

**Issue by sugarjig** [dotnet/roslyn-analyzers#2723]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.4 (Latest)

#### Diagnostic ID

AD0001

#### Repro steps

1. Upgrade FxCopAnalyzers from 2.9.3 to 2.9.4
2. Run `dotnet build`
3. Observe error

#### Expected behavior

No exception is thrown

#### Actual behavior

Build fails with
```
CSC : error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotHardCodeEncryptionKey' threw an exception of type 'System.NotSupportedException' with message 'Unexpected root operation kind: None'.
```

**Comment by mavasani** [comment]
@sugarjig do you have a repro project to share?

Tag @LLLXXXCCC @dotpaul

**Comment by mavasani** [comment]
Seems like the exception is being thrown here: https://github.com/dotnet/roslyn-analyzers/blob/ba0ff06037aeadaea2e91ccc53aee0591b6dbe06/src/Utilities/Compiler/Extensions/IOperationExtensions.cs#L451

**Comment by mavasani** [comment]
I think I have enough to go here to come up with a repro and also implement a fix.

**Comment by mavasani** [comment]
@dotpaul @LLLXXXCCC I think that the below code is executing dataflow analysis for any code with an array initializer: https://github.com/dotnet/roslyn-analyzers/blob/a1a198d1c5d2359e93dd4ab4b1c4f7421512724e/src/Microsoft.NetCore.Analyzers/Core/Security/SourceTriggeredTaintedDataAnalyzerBase.cs#L184-L200

Is that a correct observation? If so, is that desired? Or do we want some other upfront checks before marking the operation block for DFA?

The fix for this bug is unrelated to these questions, but just something I noticed while looking at the code...

**Comment by mavasani** [comment]
Verified fixed in https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.5-beta1.19380.2+0be70b2e
