### ISSUE TITLE
CA2101 triggers on non-Win32 P/Invokes

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn-analyzers#2886]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.4 (Latest Stable)

#### Diagnostic ID

[CA2101](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2101-specify-marshaling-for-p-invoke-string-arguments?view=vs-2019)

#### Repro steps

As per https://github.com/SteamRE/SteamKit/pull/726:

Run analysis on the following code:

```csharp
static class LibC
{
    const string LibraryName = "libc";

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
    public static extern int statfs64(string path, ref statfs buf);
}
```

Or:

```csharp
static class CoreFoundation
{
    const string LibraryName = "CoreFoundation.framework/CoreFoundation";

    public enum CFStringEncoding : uint
    {
        kCFStringEncodingASCII = 0x0600
    }

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
    public static extern CFTypeRef CFStringCreateWithCString(CFTypeRef allocator, string cStr, CFStringEncoding encoding);

    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi )]
    [return:MarshalAs(UnmanagedType.U1)]
    public static extern bool CFStringGetCString(CFTypeRef theString, StringBuilder buffer, long bufferSize, CFStringEncoding encoding);
}
```

#### Expected behavior

No warnings as these are P/Invoke calls to macOS system APIs, and macOS does not have the same concept of ANSI vs Unicode APIs that Windows does.

#### Actual behavior

Warning CA2101: Specify marshaling for P/Invoke string arguments

**Comment by Evangelink** [comment]
@mavasani The only thing I can see is to allow a user option for dll name which doesn't require the marshaling info. WDYT?

**Comment by dss539** [comment]
This actually is not a false positive, but the warning explanation and the proposed fix of switching to Unicode are profoundly unhelpful.  You can't just arbitrarily decide to change the string marshalling like the fix proposes.

ANSI marshalling is a security issue because the "best fit mapping" string conversion is insecure.  
There are 2 ways to work around this:
1. In the best scenario, you would switch to a Unicode capable API, but obviously that is not always possible and simply changing the `CharSet` attribute is not a magic fix.
2. The most direct solution if you _must_ use an ANSI string is just to disable best fit mapping.  
Add the parameters `BestFitMapping = false, ThrowOnUnmappableChar = true` to your `DllImport`  
If your strings can't be mapped to ANSI, you'll get an exception. That's a lot better than getting pwned, at least.

See https://stackoverflow.com/a/13369930/55721

**Comment by mwwaters** [comment]
With .NET 6, I am still getting CA2101 with BestFitMapping = false and ThrowOnUnmappableChar = true. This is a legacy DLL and the code would be broken by going calling with UTF-16 bytes.

**Comment by weezlemsneezle** [comment]
I'm having the same issue as mwwaters. I've got the following code and still get the CA2101 warning
`[DllImport(DllName, CallingConvention = CallingConvention.StdCall, CharSet = CharSet.Ansi, ThrowOnUnmappableChar = true, BestFitMapping = false)]`
This has only been an issue since upgrading to .NET 6

**Comment by philipp-naused** [comment]
We have the same problem in .NET Framework 4.8 using [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/)
`[DllImport("example.dll", CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]`
