### ISSUE TITLE
Wrong CA2000 detected, when using new using style with object initializer style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#2908]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/749928/wrong-ca2000-detected-when-using-new-using-style-w.html)._

---
When an IDisposable is created using the new using pattern, and the object initializer style at the same time, CA2000 fires, even though the instance is disposed by using using.

Here a simple example. On variable “works” the warning is not shown, but variable “worksNot” gets the warning.
The example uses VS2019.16.3.1, with .NET Core 3.0, C# 8.0 and the new Compile-Time-Analyzers.

```
using System;

namespace CA2000
{
    class Program
    {
        static void Main(string[] args)
        {
            using var works = new MyClass();
            works. Test = &quot;Test&quot;;
            using var worksNot = new MyClass {Test = &quot;Test&quot;};
        }
    }

class MyClass : IDisposable
    {
       public string Test { get; set; }

#region IDisposable

/// &lt;inheritdoc /&gt;
       public void Dispose()
       {
       }

#endregion
    }
}
```

---
#### Visual Studio Feedback System on 9/26/2019, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/3/2019, 02:39 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by StefanOssendorf** [comment]
That's not an error of this analyzer. The object initializer actually uses a temp variable.
Something like  
```
var tmp = new MyClass();
tmp. Test = "Test";
using var worksNot = tmp;
```
And since `tmp.Test` could throw an exception the new instance would not be disposed.
Here's a SO post regarding that: https://stackoverflow.com/questions/3514902/object-initializers-in-using-block-generates-code-analysis-warning-ca2000/3514928#3514928

**Comment by andre-ss6** [comment]
@StefanOssendorf Look at this however: 

```cs
        class Bar
        {
            public string Baz { get; set; } = "";
        }

        class Foo : IDisposable
        {
            public Foo(Bar bar)
            {
                Bar = bar;
            }

            public Bar Bar { get; set; } = new Bar();
            public void Dispose() { }
        }

        public void M()
        {
            using var foo = new Foo(new Bar { Baz = "baz" });
        }
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ4wxQEICGU9TjdB3/5MhhwAGUuwBetUgHMYAFwDcpAM4LlAX1IBeUgCI9irvw2Fj3CgDEIEUiFIBJACIBLFQAcIKtsAA2McyZeAQsyawgACnYoUmAOAEpAgWCQgWidWI4jPlSGUwIk/hJxDhKYmll1VSqtXQA7GAB3Moj47NzmIRRSVw8vGFbpfJD8wsFyboBZVrGU3IwxADdSgDMbDIbm8IjNsulJDL04iT1SDTax/I0gA=

It produces CA2000 when it shouldn't, since there's never a temporary created for `foo`.

**Comment by andre-ss6** [comment]
In fact, it is quite wrong. Look at this:

```cs
    class Bar
    {
        public string Baz { get; set; } = "";
    }

    class Foo : IDisposable
    {
        public Foo()
        {

        }
        public Foo(Bar bar)
        {
            Bar = bar;
        }

        public Bar Bar { get; set; } = new Bar();
        public void Dispose() { }
    }

    public void M()
    {
        {
            using var foo = new Foo(new Bar { Baz = "baz" }); // CA2000
        }

        using (var foo = new Foo(new Bar { Baz = "baz" })) // nothing (correct)
        {

        }

        using (var foo = new Foo { Bar = new Bar { Baz = "baz" } }) // nothing (incorrect)
        {

        }
    }
```
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ+VqQEICGU9jdBjf5ZDDgAMrNgC9apAOYwALgG5SAZ3lKAvqQC8pAES6FXBusJGmpAGIQIpEKQCSAEQCWygA4RlbYABsYZnn5GEktrAAoASjM+HmjGE14ggVCIMPYoUmAOKMSgwKS+dO1MjkNc/gS4hhCiopoZNRVGzR0AOxgAdzEoSLKCkIwUUhd3TxhIqQS+SvKBoYBZSICq2hW+DFEANw5SADNrYvauq1Sj7ql2SR1dLPFdUnUIpQB6Z6oAQSxhb5WZ/tEwtsMvsbG1Oikwmc6mIrnpbvdHhFSK9SK0IHIABbOVrSUhhSBQWBgOQ5AqxcrTUwU4IAoF7A5g44HepFRnnFkSYo3CQIh5IlFozHY3FhbEEokklbkgpTeKEdRAA=

It is producing a warning incorrectly and _not_ producing a warning incorrectly as well.

**Comment by StefanOssendorf** [comment]
Oh. Okay I was too hasty. Looks like a problem with the new using, yes.

**Comment by jeroen-mostert** [comment]
[Related](https://github.com/dotnet/roslyn/issues/37675). The current version of the IDE will actually offer to refactor this -- incorrectly. Rather than a general CA2000 (which will leave open questions of what is actually happening, and what the correct semantics are) a Roslyn-powered analysis could detect an inappropriate use of an object initializer and warn specifically for that. (FxCop was limited to just seeing "something" happened before the `try .. finally`, with little hint as to where the code was coming from.)

**Comment by mavasani** [comment]
Verified no repro for following tests with FxCopAnalyzers 2.9.8 and VS2019 16.4:

```csharp
using System;

class Bar
{
    public string Baz { get; set; } = "";
}

class Foo : IDisposable
{
    public Foo(Bar bar)
    {
        Bar = bar;
    }

    public Bar Bar { get; set; } = new Bar();
    public void Dispose() { }



    public void M()
    {
        using var foo = new Foo(new Bar { Baz = "baz" });
    }
}
```

```csharp
using System;

class Bar
{
    public string Baz { get; set; } = "";
}

class Foo : IDisposable
{
    public Foo()
    {

    }
    public Foo(Bar bar)
    {
        Bar = bar;
    }

    public Bar Bar { get; set; } = new Bar();
    public void Dispose() { }

    public void M()
    {
        {
            using var foo = new Foo(new Bar { Baz = "baz" }); // CA2000
        }

        using (var foo = new Foo(new Bar { Baz = "baz" })) // nothing (correct)
        {

        }

        using (var foo = new Foo { Bar = new Bar { Baz = "baz" } }) // nothing (incorrect)
        {

        }
    }
}
```
