### ISSUE TITLE
Provide a more clear overview of available analyzers and when to use what analyzer

### ISSUE THREAD

**Issue by tndata** [dotnet/roslyn-analyzers#2915]
Today I feel a bit confused about all the available analyzers and when to use what analyzer and in what context. Especially, what analyzers are included in Visual Studio, which one should I use, which one are legacy and perhaps not recommended. 

Especially I feel lost when I see all the available analyzers from Microsoft here:
https://www.nuget.org/packages?q=microsoft+analyzers

I would like to see a page giving me as an architect an overview of the available analyzers and some guidance for what analyzer to use where and when.  FxCop, Stylecop, Sonarqube, Roslynator....

what are the recommendations for a new project 2019?

**Comment by kmgallahan** [comment]
> FxCop

Refer to [this repo's documentation on its relationship to FxCop](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisfxcopanalyzers).

> I would like to see a page giving me as an architect an overview of the available analyzers and some guidance for what analyzer to use where and when.
> Stylecop, Sonarqube, Roslynator

Those are all 3rd party analyzers, so providing advice on which ones to use where and when isn't necessarily something Microsoft should do officially in this repo. 

> Especially I feel lost when I see all the available analyzers from Microsoft here:

Revise your search term to `title:analyzers owner:Microsoft` - that provides a result set of 21 instead of 10k.

The names of those 21 packages along with 2 line description should fairly clearly explain what they apply to (such as those specific to EntityFrameworkCore, AspNetCore, NetFramework, Blazor, etc.), and so you should be able to get an idea of if you might want to use them or not.

Also note that this repo's [docs mention many of them](https://github.com/dotnet/roslyn-analyzers#the-following-are-subpackages-or-nuget-dependencies-that-are-automatically-installed-when-you-install-the-microsoftcodeanalysisfxcopanalyzers-package).

**Comment by Evangelink** [comment]
@mavasani I don't see much to do here.

**Comment by mavasani** [comment]
Please see https://github.com/dotnet/roslyn-analyzers/issues/2026#issuecomment-747549515 for links to new and better official documentation on first-party and third party analyzers and blog posts.
