### ISSUE TITLE
Async Package doesn't pick up Methods that return task but are not prefixed with Async.

### ISSUE THREAD

**Issue by niemyjski** [dotnet/roslyn-analyzers#308]
For example SignalR has a Group.Add() method that returns Task. I wasn't awaiting it because I missed it.. The analyzer never picked it up..

https://github.com/exceptionless/Exceptionless/blob/f74b6ac54a6d771b280c03e0ad731a2b0293d9c3/Source/Api/Hubs/MessageBusHub.cs#L130

**Comment by tmeschter** [comment]
@niemyjski What behavior would you like to see in this case? In your example, the `OnReconnected` method returns `Task` but is not marked with `async`.

I *think* the compiler itself (rather than the AsyncPackage analyzers) would have given a warning about this if the method were marked `async`.

If that's the case, we should consider creating a general analyzer that warns about method calls that return `Task` that are never used. The AsyncPackage may not be the right place for that, but we could put it somewhere.

**Comment by niemyjski** [comment]
If the method or property returns anything awaitable we should get a warning / fix to await it.

**Comment by niemyjski** [comment]
I think it's the right package for it because it deals with async. Some people might have a naming convention where it's not prefixed with async because everything is async.. Thus the async package should still work.

**Comment by sharwell** [comment]
Related to #211. The repository referenced [does include this rule](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/blob/master/AsyncUsageAnalyzers/AsyncUsageAnalyzers/Naming/UseAsyncSuffixAnalyzer.cs).

**Comment by mavasani** [comment]
Stale issue, we do not have async usage analyzers in the repo anymore. Please use https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers/ for async/threading analyzers
