### ISSUE TITLE
Deprecate the VSIX Analysis Extension

### ISSUE THREAD

**Issue by Thieum** [dotnet/roslyn-analyzers#3314]
#### Analyzer package

N/A

#### Package Version

N/A

#### Diagnostic ID

N/A

#### Repro steps

As suggested by @mavasani in https://github.com/MicrosoftDocs/visualstudio-docs/issues/4814#issuecomment-589786353 - Considering the extension installable from https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MicrosoftCodeAnalysis2019 contains an outdated version of the analyzers, and that Visual Studio suggests its installation with the following warning: 

![image](https://user-images.githubusercontent.com/944894/75063311-a6593f00-54b2-11ea-8be9-3ff8283e83a0.png)

It can lead to analysis that are not up to date with the current state of the analyzers, or even conflicts with what the nuget packages installed in one project suggests.

#### Expected behavior

Deprecate the extension as suggested by @mavasani . It could be one last update with a null analyzer inside?

Remove the vsix install suggestion from Visual Studio, and keep only the nuget package install suggestion.

#### Actual behavior

The extension leads to false positive and other issues that are now fixed in the current analyzers.

**Comment by mavasani** [comment]
Tagging @sharwell and @mikadumont. We should do these as soon as we start shipping the .NET analyzers in the .NET SDK. Customers who are still interested in the VSIX model because they want to enable these analyzers machine wide, while working on repos that do not want to enable these in CI, can work around this by having:
1. Directory.props in their root drive which just enables .NET analyzers with an MSBuild property and
2. .editorconfig in the same drive with preferred analyzers marked as "Info" or "Suggestions"

**Comment by Evangelink** [comment]
Might overrules the need to fix #3248

**Comment by mavasani** [comment]
This needs to be prioritized given https://github.com/dotnet/roslyn/issues/44014

**Comment by mavasani** [comment]
Both VS2017 and VS2019 Microsoft CodeAnalysis VSIX extensions have been removed from the market place. Please refer to https://docs.microsoft.com/visualstudio/code-quality/install-net-analyzers?view=vs-2019 to enable CA rules from the .NET SDK or via `Microsoft.CodeAnalysis.NetAnalyzers` NuGet package.
