### ISSUE TITLE
CA1062 - Get error assigning a value to an array element

### ISSUE THREAD

**Issue by dparvin** [dotnet/roslyn-analyzers#3437]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (latest release)

#### Diagnostic ID

Example: [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019)

#### Repro steps
`    Public Sub GetValues(ByRef Values() As String)`
`          ReDim Values(0)`
`          Values(0) = "Test Value" ' <-- Error on array element`
`    End Sub`

#### Expected behavior
No error due to CA1062 being violated

The array when passed is basically a pointer to the start of the array and the ReDim will erase it and reinitialize it.

Most likely the first element in the array at this point would be a null value, but assigning something to it would at that point make it not null.

#### Actual behavior
I get a CA1062 error on the line indicated above.

**Comment by Youssef1313** [comment]
@mavasani, Can you help telling the root cause of the problem?
My initial analysis suspects a problem with `GetOrComputeHazardousParameterUsages` which is used in more analyzers, not only CA1062. Is that correct? I couldn't get how `GetOrComputeHazardousParameterUsages` exactly works and what is the root cause.
