### ISSUE TITLE
Update the Title and Description for CA1835 rules to be shared in both descriptors declared by this analyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3586]
@carlossanlop I think you may want to update the Title and Description for CA1835 rules to be shared, i.e. something like `Prefer 'ReadOnlyMemory<Byte>' overload for 'ReadAsync'/'WriteAsync'` and use it for both your descriptors.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/3581_

**Comment by carlossanlop** [comment]
No, because the `ReadAsync` method takes a `Memory<byte>` (see [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.readasync?view=netcore-3.1#System_IO_Stream_ReadAsync_System_Memory_System_Byte__System_Threading_CancellationToken_)), while the `WriteAsync` method takes a `ReadOnlyMemory<byte>` (see [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.writeasync?view=netcore-3.1#System_IO_Stream_WriteAsync_System_ReadOnlyMemory_System_Byte__System_Threading_CancellationToken_)).

**Comment by carlossanlop** [comment]
Does it cause problems to have two separate titles and descriptions? If yes, is there a way to have one with a `{0}` placeholder? That was one of the questions in my PR but IIRC the answer was that it's not possible.

**Comment by mavasani** [comment]
So basically each rule ID has to be mapped to a single title and description string. Unlike, messages we don't have the luxury to dynamically create these strings or use multiple of them for the same ID.

**Comment by mavasani** [comment]
Category, Title and Description are the core metadata for each rule ID. Messages are specific to each violation, which might have additional/differing context, hence allowed to have variations per reported diagnostic instance.

**Comment by carlossanlop** [comment]
Ok I can make the title and description texts generic enough to cover both cases. I'll address this in my current fixer PR.

**Comment by carlossanlop** [comment]
Fixed in #3592
