### ISSUE TITLE
CA2213 does not recognize an IAsyncDisposable implementaton as sufficient.

### ISSUE THREAD

**Issue by bbarry** [dotnet/roslyn-analyzers#3601]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

Example: [CA2213 ](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2213?view=vs-2019)

#### Repro steps

    internal class DbConnectionService : IDbConnectionService, IAsyncDisposable
    {
        private DbConnection? _dbConnection;
        // ...
        public async ValueTask DisposeAsync()
        {
            if (_dbConnection != null)
            {
                await _dbConnection.CloseAsync().ConfigureAwait(false);
                _dbConnection = null;
            }

            // ...
        }
    }

#### Expected behavior

No CA2213 reported

#### Actual behavior

CA2213

**Comment by Evangelink** [comment]
I did some tests and the actual problem is `CloseAsync` not being recognized as an equivalent of the `DisposeAsync`.

We could assume that all parameterless `CloseAsync` methods returning a `Task` and available on a type implementing `IAsyncDisposable` have the same effect as `DisposeAsync`. We could also have a white-list and a user-option for providing extra methods but I think that the first assumption is good enough. 
@mavasani WDYT?

**Comment by mavasani** [comment]
Yes, let’s start by detecting CloseAsync.

**Comment by bbarry** [comment]
Huh I hadn't realized I called close instead of dispose. My code no longer triggers with that change. I guess I can leave it open if you want to detect CloseAsync.

**Comment by Evangelink** [comment]
@bbarry Yeah let's keep this open I will push a PR for this today :)
