### ISSUE TITLE
False positives CA2235 on 3.0.0

### ISSUE THREAD

**Issue by kamyker** [dotnet/roslyn-analyzers#3616]
Same issue as in #1712, for me for strings #1936

**Comment by DrkWzrd** [comment]
Same issue, with fields of type that implements ISerializable, but not have SerializableAttribute (Dictionary, List, HashSet etc...)

![image](https://user-images.githubusercontent.com/40547839/83509456-c04fe800-a4cb-11ea-94b0-ece993f5713a.png)

**Comment by Evangelink** [comment]
@mavasani Would it be possible to publish a new version of the packages on myget to ensure the bug is fixed? I am wondering if this PR #3319 didn't fix the issue.

**Comment by mavasani** [comment]
@kamyker @DrkWzrd Can you make sure that you have not installed "Microsoft CodeAnalysis 2019" VSIX extension? That has older analyzer bits and _will_ have this false positive. We are planning to deprecate that extension soon.

@Evangelink The issue was validated as fixed prior to #3319. Do you think it could have regressed with that PR? We are planning to publish 3.3.0-beta1 packages soon, but I am not sure if that will help the customers here.

**Comment by kamyker** [comment]
@mavasani yes, I use "Microsoft CodeAnalysis 2019" as Unity doesn't support NuGet packages and probably it's impossible to use that version as Unity regenerates solution.

> We are planning to deprecate that extension soon.
Any idea how to use nuget version it with Unity? Project properties are not available as showed on
https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019

**Comment by DrkWzrd** [comment]
@mavasani Yeah, I had it installed. I'm going to test without it. Thanks!

**Comment by Evangelink** [comment]
@mavasani I think the ticket can be closed.
