### ISSUE TITLE
VS is telling me to use Configure await but i can't.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#3688]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1046936/vs-is-telling-me-to-use-configure-await-but-i-cant.html)._

---
I have an abstract class (Renderer) that provides for it's child class to define a build workload ..

```csharp
public Func<Task> Build { get; set; }
```

This workload is called at the appropriate time in a build function ..

```csharp
internal async void OnBuild()
{
    ...
    // run child class build workload
    await Build?. Invoke();
    ...
}
```

In the previous code, VS is telling me to consider calling ConfigureAwait on the awaited task, but that's not possible because ..

CS1929	'ConfiguredTaskAwaitable?' does not contain a definition for 'GetAwaiter' and the best extension method overload 'WindowsRuntimeSystemExtensions.GetAwaiter(IAsyncAction)' requires a receiver of type 'IAsyncAction'

Is this something I'm doing wrong, perhaps I need to implement some functionality or is VS just wrong in suggesting this change?

---
#### Visual Studio Feedback System on 5/25/2020, 02:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by svick** [comment]
> Is this something I'm doing wrong

Kind of. There is no point to use `?.` here, because `await`ing a `null` `Task` still causes a `NullReferenceException`.

Though it's also true that VS shouldn't recommend you to change your code to something that doesn't compile. And I think it would be valuable if you got a warning that this kind of code is problematic.

**Comment by Evangelink** [comment]
Is your `Func` returning `Task`? If so the following bit of code works for me:

```csharp
private class C
{
    public Func<Task> Build { get; set; }

    internal async void OnBuild()
    {
        await (Build?.Invoke()).ConfigureAwait(false);
    }
}
```

**Comment by Gavin-Williams** [comment]
The following work's by the way and is equivalent code as far as I'm concerned.
```
            if (Build != null)
                await Build().ConfigureAwait(true);
```
To me, they both read "If the function Build is not null, then invoke the function. At least, that is the way I use the compact null check:  ?.

I feel like Build.?Invoke() should definitely resolve first to either become null and break out or become Build() and be awaitable. In other words, I would think that Build?.Invoke() is the object here. Is VS traying to read it as Invoke() is the object that I'm trying to ConfigureAwait() on?

Yes, it's a Func<Task>. And thanks for realizing that enclosing with braces makes it work. I hadn't thought of that.

Interestingly, if I use Quick Action, VS will wrap the code in braces correctly. I just can't make sense of why the brackets are needed, but I least I can see how to make it work now.

**Comment by svick** [comment]
@Gavin-Williams 

> I feel like Build.?Invoke() should definitely resolve first to either become null and break out or become Build() and be awaitable.

That this pretty much how it works, though it only "breaks out" of the `Build?.Invoke().ConfigureAwait(false)` expression, not the whole `await` statement. And "breaking out" means that the whole expression becomes `null`. But `ConfigureAwait` returns a value type (`ConfiguredTaskAwaitable`), so the whole expression becomes nullable value type (`ConfiguredTaskAwaitable?`). But `await` doesn't work on that, which is why you get a compile error.

On the other hand, if you use parentheses, it only "breaks out" of that part of the expression, which is why the code compiles (but can throw `NullReferenceException` at runtime).

Maybe it will be clearer if I translate `?.` into the ternary operator. Using that,

```c#
await Build?.Invoke().ConfigureAwait(false);
```

becomes roughly:

```c#
await (Build == null ? null : Build.Invoke().ConfigureAwait(false));
```

While

```c#
await (Build?.Invoke()).ConfigureAwait(false);
```

becomes more like:

```c#
await (Build == null ? null : Build.Invoke()).ConfigureAwait(false);
```

(Note that these translations are not 100 % accurate, but they should get the idea across.)

> Interestingly, if I use Quick Action, VS will wrap the code in braces correctly.

From the original post, I got the impression that it didn't and that the Quick Action produced the wrong code. If that's not the case, I'm not sure there's much to do here.

**Comment by sharwell** [comment]
I was not able to reproduce this error. The code fix added parentheses for me.

**Comment by svick** [comment]
@genlu @sharwell Your label changes here, which were made at the same time, seem to conflict with each other: I don't think a closed issue should be labeled as "help wanted".
