### ISSUE TITLE
ca1062 false positive in "OnXXXX(XXX e)" methods

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/roslyn-analyzers#3715]
#### Package Version
v3.0.0 (Latest)

#### Diagnostic ID
CA1062, null check arguments

#### Repro steps
Inherit from FrameworkElement, override some method with arguments
Don't check if arguments are null

#### Expected behavior
No fire CA1062 warning

#### Actual behavior
![image](https://user-images.githubusercontent.com/40547839/83952928-cc75d580-a83c-11ea-9b7c-df594fbdb933.png)
![image](https://user-images.githubusercontent.com/40547839/83953028-62a9fb80-a83d-11ea-8447-73055fe1096d.png)

**Comment by Youssef1313** [comment]
I don't get what prevents the argument from being null?
I think there is a possibility that DrawingContext or MouseButtonEventArgs being null. (You may call the method by yourself and pass `null`)

**Comment by Evangelink** [comment]
@Youssef1313 You are right! At the same time, if you don't expose your controls you _know_ that you won't receive any `null`.

**Comment by DrkWzrd** [comment]
@Youssef1313 @Evangelink I'm don't know if Analyzer can check references of use. If it could and the number is 0 (in other words, "none of your code use this element directly"), the warning is useless, because the argument never will be null.

**Comment by mavasani** [comment]
@DrkWzrd This is a public API - the library cannot control if some external client can invoke a public API with null input or not. The analyzer is designed to suggest all public APIs to validate arguments - if you feel it is not applicable for a specific API, you should add a source suppression. If you feel this rule is not applicable for your project, you can disable it in editorconfig or with a nowarn. The current CA1062 behavior is by design.
