### ISSUE TITLE
[Question] Adding analyzers to multiple projects in solution via project reference / class lib

### ISSUE THREAD

**Issue by NielsKruse** [dotnet/roslyn-analyzers#3758]
(Sorry for hijacking the issues for a mere question)

Instead of adding a bunch of analyzers (FxCop, Roslynator, SecurityCodeScan, Sonar) to each project in a solution, I wanted to, maybe, create a class lib and add them via project reference, so that I can at least maintain the referenced analyzers in one place.
I also created a ruleset file for the entire solution that each project includes via prop.
Last thing I tried was this...
```
  <ItemGroup>
    <ProjectReference Include="..\MyStuff.CodeQuality\MyStuff.CodeQuality.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Analyzer</OutputItemType>
    </ProjectReference>
  </ItemGroup>
```
... that made the project dependency show up under analyzers in the respective projects, but does not "run" the analyzers.

Any ideas, if a central "code quality" lib/project is at all possible?

**Comment by Evangelink** [comment]
@NielsKruse The most common pattern is to use the `Directory.Build.props` file to declare your analyzers. I am doing that on my projects and that's also what is used here. Note that you will have to be careful when updating the nuget from the nuget manager because it will add them in each projects instead of updating the `Directory.Build.props` file.

More info about the [Directory.Build.props file](https://docs.microsoft.com/visualstudio/msbuild/customize-your-build).

**Comment by NielsKruse** [comment]
Very nice. Thank you for pointing me at it.
I also see what you're saying about NuGet. Need to make mental note to set the version number in the .props file. ^^
