### ISSUE TITLE
CA1052 False Positive

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3803]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

Example: [CA1052](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1052)

#### Repro steps

Have a class that all its members are static, but the class itself isn't static. Use this class as a type argument. The analyzer suggests to make this class static, but it cannot be made static as it's used as a type argument.

For easier repro:

1. Use the default ASP.NET Core Empty project template from [here](https://github.com/dotnet/aspnetcore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp) or create it from Visual Studio.
2. Install the latest analyzers package.
3. Open Startup.cs, the analyzers will suggest marking its method as static.
4. After marking the methods static, the analyzer CA1052 will suggest marking the class itself static.
5. After marking the class static, there will be a compile error in Program.cs

#### Expected behavior

CA1052 not reported if the class is used as type argument.

#### Actual behavior

CA1052 is reported, causing a compile error where the class is used as a type argument:

![image](https://user-images.githubusercontent.com/31348972/86234354-12515f80-bb97-11ea-9e41-16c6180cc613.png)

**Comment by mavasani** [comment]
This is by design, and similar to https://github.com/dotnet/roslyn/issues/44330#issuecomment-631487553. Detecting such uses within a project would make this a build-only analyzer like [CA1812](https://docs.microsoft.com/visualstudio/code-quality/ca1812?view=vs-2019), as we would need to analyze the whole project. We still cannot catch cases where a public/internal type is used this way in referencing projects. Given these cases are rare, correct resolution here is for the users to add a source suppression for CA1052 with proper justification comment which acts as a documentation for future developers.

**Comment by Youssef1313** [comment]
@mavasani Sounds good. Thanks. I think this case can be added to the documentation under "When to suppress". I'll close this issue and open a PR to update the docs.
