### ISSUE TITLE
Add AnalysisLevel MSBuild property

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-analyzers#3823]
There will be a central MSBuild property that can be used to configure what /warnversion is passed to the compiler. 
Tentatively call AnalysisLevel for now
- This will need to be plumbed through VS tooling including property pages
- Would also like to remove “Warning Level” from the VS Build property pages in favor of this

Related to https://github.com/dotnet/roslyn/issues/45701

**Comment by sbomer** [comment]
We plan to respect `AnalysisLevel` for ILLink as well. Would you be able to share more details on the VS UI for this? I'm wondering if it's going to set `AnalysisLevel`, and whether the plan is still to remove "Warning Level" in favor of a new UI, now that the compiler implementation is reusing the `/warn` option instead of introducing a new `/warnversion`.

**Comment by jmarolf** [comment]
@sbomer as of now, the design is that `/warn` is only for controlling compiler produced diagnostics. `AnalysisLevel` is for controlling third-party tools that feed in diagnostics like analyzers (and presumably ILLink). `/warn` will still exist for compiler config (behind the advanced button in the UI) but I would expect the new `AnalysisLevel` drop down to be the main way users would configure this.
