### ISSUE TITLE
Please disable CA1815 with ref struct.

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/roslyn-analyzers#3825]
[CA1815](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1815?view=vs-2019)
Is enabled for ref structs and while they can implement `==, !=` and `Equals([ref] other)` I don't think they can implement anything else.

**Comment by mavasani** [comment]
I believe this was fixed by @Evangelink in https://github.com/dotnet/roslyn-analyzers/pull/2978. @juliusfriedman how are you getting your analyzers? If through FxCopAnalyzers NuGet package, then this package should have the fix: https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/3.3.0-beta1.final

**Comment by juliusfriedman** [comment]
I was on:
![image](https://user-images.githubusercontent.com/7851618/86773246-66d75d80-c023-11ea-9716-3537a7fd597a.png)
I just updated to the indicated version.

VS 2019 installs the version I had by default...
