### ISSUE TITLE
Report a warning when user has a package reference to an older version of .NET SDK analyzers then built-in ones in the .NET SDK

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3977]
Follow-up to https://github.com/dotnet/roslyn-analyzers/pull/3974. That PR ensures that users can override/de-couple built-in .NET analyzers with an explicit analyzer NuGet package reference. We should build on that to warn users when they move to an SDK with newer version of analyzers then the one they have installed with the explicit NuGet package reference.

> I’d say the SDK should have a static property that indicates which version of the package it has ingested. When the package is installed, it should compare its own version number with that. If it’s equal or higher, no warning. If its lower, issue a warning like this:
WARNING: The .NET SDK has newer analyzers then what is provided by version x.y.z of this package. Update or remove this package reference.

**Comment by mavasani** [comment]
@jmarolf I can take this up if you point out to me the MSBuild property that can be used to identify the version of analyzer assembly in the SDK. If such a property does not exist today, suggest a name that you plan to add to the SDK and I can use that here.

**Comment by jmarolf** [comment]
hmm, I propose that each of the props files (both the one that ships in the sdk and the one that ship in the nuget package) write out their build number as part of the signed build. Otherwise we would need to call .NET methods from msbuild to get the assembly version which seems un-necessarily slow. Then you can just check
1. is the version property already defined
2. is it greater then mine
3. if so issue a warning

Since this logic will be in both the SDK props we insert and the nuget package props it would gurantee that the warning gets triggered.

**Comment by mavasani** [comment]
Great, that sounds like a good idea! I will implement this early next week.
