### ISSUE TITLE
RS1026 (Enable concurrent execution) false positive for empty Initialize method

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#4102]
### Analyzer

**Diagnostic ID**: [RS1026](https://docs.microsoft.com/visualstudio/code-quality/rs1026): **Enable concurrent execution**

### Analyzer source

**Version**: v3.3.0 (Latest)

### Describe the bug

RS1026 should not be reported for empty `Initialize` methods, e.g.:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/441ef9728ef0ffc529b784fbde51b5ea7be98ecf/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1603DocumentationMustContainValidXml.cs#L41-L46

🔗 See also #4101

**Comment by mavasani** [comment]
This is by design as per https://github.com/dotnet/roslyn-analyzers/issues/4101#issuecomment-692820153. SA1603 adds unnecessary performance overhead with no user value add, it must be removed from the analyzer package.

**Comment by Evangelink** [comment]
@mavasani Any reason to keep the tickets open?

**Comment by mavasani** [comment]
Waiting for Sam’s confirmation on it.

**Comment by Evangelink** [comment]
@sharwell Could you confirm this can be closed?

**Comment by mavasani** [comment]
As mentioned in https://github.com/dotnet/roslyn-analyzers/issues/4101#issuecomment-692820153 this is actually by design and helps avoid stub analyzers which return non-zero descriptors but have an empty Initialize method. This incurs an unnecessary performance cost of instantiating a no-op analyzer. Please fix the analyzer package or add a source suppression.

**Comment by sharwell** [comment]
@mavasani if we need a rule to avoid stub analyzers, we should have a rule to avoid stub analyzers. The messaging provided by RS1026 is not useful to analyzer authors in this context.

**Comment by Evangelink** [comment]
I agree with @sharwell here. Having the issue while you are building is annoying and if it is a problem to have empty initialize then it could be another rule (besides it could be a non-analyzer specific rule that prevents empty block).

**Comment by mavasani** [comment]
> if we need a rule to avoid stub analyzers, we should have a rule to avoid stub analyzers

@sharwell Over a decade of analyzer support, only StyleCop analyzers ships stub analyzers with no implementation. Why are we hurting the simplicity of analyzers (enabled analyzers must be configured) by adding special case for an analyzer package which took a decision to go against design guidelines for analyzers and ship stub no-op analyzers.

**Comment by mavasani** [comment]
> Having the issue while you are building is annoying 

Yes, so analyzer author should add a source suppression that acts as a documentation that I am explicitly choosing to not configure my analyzer because of xyz special case. I don't believe adjusting analyzers for every single un-common and not recommended use case is the way to go forward. If we strongly feel about this, feel free to reopen the issue and bring it to design meeting. I would ideally like to see at least 1 more realistic customer request on this.

**Comment by mavasani** [comment]
I have also not been given a valid reason that justifies shipping a stub analyzer that incurs performance cost on users but is basically a no-op analyzer. Using this mechanism for deprecated analyzers is discouraged, instead the docs for deprecated analyzer rules should be published so when users search for it online, they find out that it has been deprecated.
