### ISSUE TITLE
Improve code fixer heuristic employed by CA1835

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#4235]
### Analyzer

**Diagnostic ID**: [CA1835](https://docs.microsoft.com/visualstudio/code-quality/ca1835)

### Describe the improvement

The analyzer currently suggests changing a call like:
```C#
await stream.ReadAsync(buffer, 0, buffer.Length);
```
to instead be:
```C#
await stream.ReadAsync(buffer.AsMemory(0, buffer.Length));
```

While correct, for the common case of a 0 offset and a length equal to the buffer's length, it is more complex than needed (with a bit more overhead, and could instead be just:
```C#
await stream.ReadAsync(buffer);
```

### Describe suggestions on how to achieve the rule

Apply a simpler code fix if the second argument is 0 and the third argument is just a Length property accessor on the first argument.

cc: @carlossanlop, @jeffhandley

**Comment by carlossanlop** [comment]
Thanks @stephentoub, this is a good improvement to consider.

It would apply for both `ReadAsync` and `WriteAsync`, since in both cases, it would make sense to use `0` as the `offset` parameter, and `buffer.Length` as the `count` parameter.

Question - How smart do we want this to be? For example, if the user saves the `buffer.Length` into a variable, and passes this variable as the `count` parameter, should the analyzer check if the variable's original value is `buffer.Length`?:
  ```cs
  int length = buffer.Length;
  stream.WriteAsync(buffer, 0, length);
  ```
My gut says that maybe we don't want to invest in adding this level of complexity, but let me know if we should.

I'll assign this to myself.

**Comment by stephentoub** [comment]
> if the user saves the buffer.Length into a variable, and passes this variable as the count parameter, should the analyzer check if the variable's original value is buffer.Length?:

I don't think that's necessary or worth additional complexity (at least not until we get evidence that it would meaningfully help). The common case, at least for ReadAsync, is to just do `buffer, 0, buffer.Length`.
