### ISSUE TITLE
CA1062 should check .NET [NotNull] attribute

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/roslyn-analyzers#4248]
### Analyzer

**Diagnostic ID**: [CA1062](https://docs.microsoft.com/visualstudio/code-quality/CA1062)

### Describe the improvement

The rule CA1062 currently checks for attributes named `ValidatedNotNullAttribute` on guard/validate methods to determine if a parameter has been checked for `null` - like so:

```c#
public static class Guard
{
    public static void IsNotNull<T>([ValidatedNotNull] T value, string paramName)
    {
        if (value is null)
        {
            throw new ArgumentNullException(paramName);
        }
    }
}

...

public void MyMethod(string someValue)
{
    Guard.IsNotNull(someValue, nameof(someValue);

    if (someValue.Length > 0) // member access is ok
    ...
}
```

The class `ValidatedNotNullAttribute` is not part of .NET itself. Instead it has to be implemented by the user themselves.

Since C# 8 (.NET Standard 2.1, .NET Core 3.0), .NET comes with the [NotNullAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute) that does exactly the same thing:

> Specifies that an input argument was not `null` when the call returns.

So, CA1062 should check for this attribute as well.

### Describe suggestions on how to achieve the rule

At the same places where CA1062 currently checks for the `ValidatedNotNullAttribute`, it should also check for `System.Diagnostics.CodeAnalysis.NotNullAttribute`.

### Additional context

See also: https://github.com/dotnet/csharplang/discussions/3954

**Comment by manfred-brands** [comment]
This works on platforms that have `NotNullAttribute` defined (netstandard2.1, netcoreapp3.1, net5.0), but not on platforms that use [Nullable](https://www.nuget.org/packages/Nullable/), [ReferenceAssemblyAnnotator](https://www.nuget.org/packages/TunnelVisionLabs.ReferenceAssemblyAnnotator/1.0.0-alpha.160) or otherwise define an `intern` version of `NotNullAttribute` to get nullable support for other targets (netstandard2.0 or net48).

I created a minimal [repository](https://github.com/manfred-brands/CA1062) to show this.
The only option that suppresses CA1062 is to define ones own *public* `NotNullAttribute`, which will have conflicts if other assemblies to the same.

Ideally the dotnet team should make a System.Diagnosictics.Nullable nuget package available.
In the mean time, could the 2nd compare in [ParameterValidationDataFlowOperationVisitor](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs#L122-L124) be changed similar to the first, but include namespace as to not confuse with JetBrains.Annotations.NotNullAttribute.

**Comment by skrysmanski** [comment]
@manfred-brands 

> The only option that suppresses CA1062 is to define ones own public NotNullAttribute, which will have conflicts if other assemblies to the same.

Back in the day (CA1062 is very old) you would create your own `ValidatedNotNullAttribute`. You can still do this today. And you won't get any conflicts because the namespace of the attribute doesn't matter.

**Comment by manfred-brands** [comment]
@skrysmanski Yes, that is what he had done in the past. We were hoping with the nullability changes we no longer needed this in every assembly with a validator. Now the [NotNull] attribute check only works for >= netstandard2.0. Unfortunately we all still have to maintain compatibility so that code can run on net framework 4.8. Even though nullability works there, CA1062 seems to be the only that doesn't which is a pity.
