### ISSUE TITLE
CA5399 should check member presence

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn-analyzers#4329]
### Analyzer

**Diagnostic ID**: [CA5399](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5399): `Definitely disable HttpClient certificate revocation list check`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

CA5399 fires on net461, which doesn't has the property `HttpClientHandler.CheckCertificateRevocationList`.

### Expected behavior

CA5399 should only fire if the member is present.

**Comment by Evangelink** [comment]
@dotpaul Could you confirm that we do want to disable the rule for this case and not only suggest a different fix?

**Comment by dotpaul** [comment]
Sorry, I started looking at this but it fell off my radar.

Seems like in .NET 4.6.1, the default is **not** checking whether the server TLS certificate is revoked. So the analyzer is working by design.

I'll have to ponder what the docs should say in the case of older version of .NET Framework (just upgrade, or is there an alternative).

**Comment by Evangelink** [comment]
Ping @dotpaul

**Comment by dotpaul** [comment]
I'll update the CA5399 docs to mention the need to upgrade the target framework if `CheckCertificateRevocationList` isn't available.
