### ISSUE TITLE
Warning when comparing 2 doubles or floats

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#4480]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1209518/warning-when-comparing-2-doubles-or-floats.html)._

---
When comparing 2 doubles or 2 floats using ==, the IDE should give a warning and suggest that an epsilon should be used

---
#### Feedback Bot on 10/8/2020, 11:32 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mavasani** [comment]
@jinujoseph I don't think this should an analyzer. If at all, this should be a compiler warning within a warning wave. Can we please move this back to Roslyn under compilers area path?

**Comment by Evangelink** [comment]
ping @jinujoseph

**Comment by sharwell** [comment]
@mavasani Let's keep it here for now but ask compiler team if they would consider it under a warning wave. If they say no (which I would expect and encourage since this problem is not specific to any one language), then this is the repository seems like the right place for it.

**Comment by jaredpar** [comment]
Zero chance we would consider this is a warning wave. Comparing `double` and `float` has a well defined specification, has been in the language since 1.0 and is supported across many other .NET languages. There is nothing incorrect or even dangerous about using `==` with floating point types as compared to other operations with floating point types. Yes floating point types have some odd corner cases you need to consider but that extends beyond `==` and is simply inherent to the underlying type. 

Further the `==` is in high valid use within our customer base. Making this a warning wave would guarantee that the majority of our customers get warnings for code they've had in production for possibly two decades (and that is not wrong). 

I'd further push back strongly on us doing this as an analyzer. The false positive rate here would be enormous.

**Comment by mavasani** [comment]
Closing as Won't fix based on Jared's comment.

**Comment by Evangelink** [comment]
@jaredpar For the sake of my curiosity, I am not sure I totally understand your comment. Are you saying that there is no problem of direct comparison with equality on floating points or are you saying that this imprecision error is something people are used to (and so have tuned the code around) and so problem exists but is not something we want to warn about?

I think the origin of this suggestion is based on the following [ReSharper rule](https://www.jetbrains.com/help/resharper/CompareOfFloatsByEqualityOperator.html) and I have to say that I was/am following this rule (it seems bindly).
