### ISSUE TITLE
Decide which analyzer to keep: CA1801 vs IDE0060

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#4498]
### Analyzer

**Diagnostic ID**: [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801)

### Describe the improvement

Currently 2 rules compete and they have both different implementation and "scope" (findings and issues), rather than "wasting" time maintaining both I would suggest that a clear cut is made and only one is kept. When the choice is made, we should ensure that the winning rule is correctly matching both scopes.

Tagging @mavasani

**Comment by Youssef1313** [comment]
IDExxxx rules are more about coding style, I don't think this rule is a stylistic-related choice. So my opinion would be to keep it as CA1801.

**Comment by mavasani** [comment]
> IDExxxx rules are more about coding style, I don't think this rule is a stylistic-related choice. So my opinion would be to keep it as CA1801.

@Youssef1313 That is a true statement for almost all cases, but we have a grey area when it comes to unnecessary code rules. Many customers see it at a style enforcement where they prefer seeing faded code in IDE for unnecessary things such as unnecessary usings, code blocks, assignments, etc. I would primarily vote for keeping IDE0060 and deprecating CA1801 for following reasons:
1. We have large number of unnecessary code rules write an IDExxxx style rules: see https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/unnecessary-code-rules and `CA1801` seems to maybe the only CA quality rule for unnecessary code.
2. IDE0060 has superior implementation: It is based on flow analysis and also identifies cases where a parameter's initial value is never read and flags it if parameter has a read after write on all code paths. It also has better messaging when flagging public APIs as a potential breaking change: https://github.com/dotnet/roslyn/blob/e78a4a6ee01500e27db35b97fad29da744cfb00a/src/Analyzers/CSharp/Tests/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs#L1084-L1127

**Comment by Evangelink** [comment]
How to move forward from here @mavasani?

**Comment by mavasani** [comment]
@Evangelink Let's do couple of things:

1. Update the docs for CA1801 to mention it is deprecated in favor of https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0060. For example, see the note added to this deprecated rule: https://docs.microsoft.com/visualstudio/code-quality/ca1009?view=vs-2019#cause. You probably also want the note to mention how users can enforce IDE0060 on the build - basically follow the steps at https://docs.microsoft.com/dotnet/fundamentals/code-analysis/overview#code-style-analysis, but with IDE0060 instead of IDE0040 in that example.
2. Make a change in release/6.0.1xx-preview1 branch to remove CA1801 analyzer and unit tests

**Comment by mavasani** [comment]
I see that doc PR was also completed. Closing this issue (note it was not auto-closed by github as the removal PR did not target master branch).
