### ISSUE TITLE
CA1714 and CA1717 rules are missing

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#4567]
### Analyzer

**Diagnostic ID**: [CA1714](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1714): `Flags enums should have plural names`
**Diagnostic ID**: [CA1717](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1717): `Only FlagsAttribute enums should have plural names`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.1 (Latest)

### Describe the bug

CA1714 and CA1717 rules are missing in NET Analyzers 5.0.1.

### Steps To Reproduce

1. Create a project and enable NET Analyzers.
2. Try to configure rules CA1714 and CA1717.

### Expected behavior

CA1714 and CA1717 rules should be present.

### Actual behavior

CA1714 and CA1717 rules are missing.

**Comment by Youssef1313** [comment]
@mavasani Should Microsoft.CodeAnalysis.NetAnalyzers reference Text.Analyzers?

**Comment by mavasani** [comment]
@avivanoff @Youssef1313 This is by design. These two spell check rules have been moved to Text.Analyzers (package might be renamed later when ready for release). We are likely to add more spell check rules in this package and release it in future.

**Comment by Youssef1313** [comment]
@mavasani Should the documentation reflect that?

**Comment by mavasani** [comment]
@Youssef1313 Which documentation? CA rules doc pages are now package/tool agnostic - they have no mention of which package they belong to, so I think we are fine.

**Comment by avivanoff** [comment]
You may be fine, but how do we supposed to know this? I am migrating to NET Analyzers, and all of a sudden some rules are gone. Isn’t it at least supposed to be mentioned in migration docs?

**Comment by shadow-cs** [comment]
@avivanoff I feel your pain. But I also do understand @mavasani that not a lot of people use FxCop but for a few of us that do, I don't feel the migration to be easy to do. We're also migrating from `ruleset` to `.editorconfig` and one doesn't know which step of the migration caused the rule to stop reporting.

When in doubt one should first consult https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md if unsure whether some specific rule is included (the link is part of the [docs](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/) I just want to emphasize that).

Also for anyone doing the transition, if your `ruleset` did include some Child ruleset `<Include Path="xxx.ruleset" Action="Default" />` (like `MinimumRecommendedRules.ruleset`) keep in mind to convert it as well and merge with `.editorconfig` since this is not done by the tools (or it didn't work for us) converting `ruleset`s to `.editorconfig`. Also keep in mind that not all rules from these `ruleset`s were necessarily implemented by FxCop analyzers (as far as I can tell).

Sort of related to #4351.

**Comment by JeppeSN** [comment]
To make it absolutely explicit, the precise package one needs to refer, to get CA1714 and CA1717, is:

[Text.Analyzers](https://www.nuget.org/packages/Text.Analyzers)
