### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers 3.3.2 vs. Microsoft.CodeAnalysis.NetAnalyzers 5.0.1

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#4569]
Is it possible to use Microsoft.CodeAnalysis.NetAnalyzers 5.0.1 package with the projects that target earlier versions of .NET (.NET Standard, .NET Framework, .NET Core), or do I have to use Microsoft.CodeAnalysis.FxCopAnalyzers 3.3.2?

**Comment by mavasani** [comment]
Please see the Note in the top section at https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview

The .NET Analyzers are platform agnostic.

**Comment by avivanoff** [comment]
https://github.com/dotnet/roslyn-analyzers#recommended-version-of-analyzer-packages says that for 5.0.1 “Required .NET SDK Version: .NET 5.0 SDK or later”.

**Comment by mavasani** [comment]
It reqruires the underlying compiler that ships with .NET5 SDK and also with VS2019 16.8.

**Comment by avivanoff** [comment]
I am still confused.
So, my original question: can Microsoft.CodeAnalysis.NetAnalyzers 5.0.1 package be used with the projects that target earlier versions of .NET (.NET Standard, .NET Framework, .NET Core)?

**Comment by ArturDorochowicz** [comment]
> It reqruires the underlying compiler that ships with .NET5 SDK and also with VS2019 16.8.

Is it so? I have installed it via the package into netcoreapp3.1 project built with 3.1.404 SDK and it builds. What kind of issues should I be expecting if it's really not compatible?

**Comment by mavasani** [comment]
> Microsoft.CodeAnalysis.NetAnalyzers 5.0.1 package be used with the projects that target earlier versions of .NET (.NET Standard, .NET Framework, .NET Core)?

Yes, installing the NuGet package enables the analyzers on all .NET platforms.

> I have installed it via the package into netcoreapp3.1 project built with 3.1.404 SDK and it builds.

The analyzers themselves are built on top of compiler APIs that shipped with VS2019 16.3, and also shipped in prior .NET SDKs, so this does not seem surprising.

> What kind of issues should I be expecting if it's really not compatible?

Analyzers themselves would likely work on prior versions of compiler/VS/.NET SDK. However, there are bunch of new analyzer configuration features added recently to the compiler. For example, [AnalysisMode](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismode) functionality is built using the [Global AnalyzerConfig](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig) files, which was first fully supported in VS2019 16.8 and .NET 5.0 SDK, so that property will likely not work as expected in prior releases.

**Comment by Evangelink** [comment]
To complement @mavasani answer, the target framework of your project doesn't matter, what matters is the building tool (msbuild, visual studio, or dotnet) you use. This tool needs to be up to a certain version to have all features otherwise some recent configurations might not work (if all you are using is `ruleset` file then you should not have any problem).

**Comment by avivanoff** [comment]
@mavasani, @Evangelink, It would be nice if documentation was updated with these details.

**Comment by mavasani** [comment]
@avivanoff We did add a NOTE in the migration page: https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers

![image](https://user-images.githubusercontent.com/10605811/102127648-9d4eab00-3e01-11eb-9634-0e8673db755b.png)

**Comment by ArturDorochowicz** [comment]
> @avivanoff We did add a NOTE in the migration page: https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers

If I were nitpicky, I could point out that a sentence before that note says "**If you don't want to move to the .NET 5+ SDK** or if you prefer a NuGet package-based model, **the analyzers are also available in the Microsoft.CodeAnalysis.NetAnalyzers NuGet package**", which to me suggests that it works with .net sdk <5 and doesn't indicate any caveats.

**Comment by mavasani** [comment]
> > @avivanoff We did add a NOTE in the migration page: https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers
> 
> If I were nitpicky, I could point out that a sentence before that note says "**If you don't want to move to the .NET 5+ SDK** or if you prefer a NuGet package-based model, **the analyzers are also available in the Microsoft.CodeAnalysis.NetAnalyzers NuGet package**", which to me suggests that it works with .net sdk <5 and doesn't indicate any caveats.

IMO, current wording is clear, but tagging our doc experts @Mikejo5000 @gewarren for doc feedback.

**Comment by Evangelink** [comment]
Ping @Mikejo5000 and @gewarren

**Comment by Mikejo5000** [comment]
Regarding features like AnalysisMode, the VS docs generally specify that VS 2019 16.8 is required. For <5 .NET SDK, the wording seems OK to me. I would be inclined to leave it as-is.
