### ISSUE TITLE
Enable or delete skipped tests

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4705]
The purpose of the following skipped tests is unclear to me.

https://github.com/dotnet/roslyn-analyzers/blob/1ead3c96987ec6200209ab602529b9bab573833d/src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OverrideGetHashCodeOnOverridingEqualsTests.cs#L60-L78

Code in them generates couple compile errors. e.g:

```csharp
  Message: 
    Microsoft.CodeAnalysis.Testing.Verifiers.EqualWithMessageException : Context: Diagnostics of test state
    Mismatch between number of diagnostics returned, expected "0" actual "3"
    
    Diagnostics:
    // /0/Test0.vb(3) : error BC30270: 'Public' is not valid on an interface method declaration.
    DiagnosticResult.CompilerError("BC30270").WithSpan(3, 5, 3, 11).WithArguments("Public"),
    // /0/Test0.vb(4) : error BC30603: Statement cannot appear within an interface body.
    DiagnosticResult.CompilerError("BC30603").WithSpan(4, 9, 4, 20),
    // /0/Test0.vb(5) : error BC30603: Statement cannot appear within an interface body.
    DiagnosticResult.CompilerError("BC30603").WithSpan(5, 5, 5, 17),
```

**Comment by Evangelink** [comment]
Ticket on roslyn side is about implicit class. I have to admit I don't know enough VB.NET to know if we can have an implicit interface implementation with this syntax in VB.NET.

**Comment by Youssef1313** [comment]
@Evangelink I think VB.NET doesn't support this.

**Comment by Youssef1313** [comment]
Tagging @amcasey who wrote the analyzer and these tests in #743 and may have some information.

**Comment by amcasey** [comment]
That was 5 years and 2 teams ago, but my guess is that the test was supposed to confirm that the new analyzer did not report diagnostics for those code fragments.  Of course, it's quite possible that the fragments produce _other_ diagnostics.  I may have left those out of the baseline on the assumption that a new baselines would be generated when they were unskipped.  https://github.com/dotnet/roslyn/issues/7305 seems to be about adding interactive-mode support for features, so it's possible that these tests are too broken to even reach the new analyzer without the anticipated support.  I'd look for a corresponding C# test (which might only survive in the PR you linked since the analyzer appears to be VB-only) - this was probably a direct port.

**Comment by mavasani** [comment]
Let's delete these tests and close the linked Roslyn issue as we are not planning to support scripting in VB.
