### ISSUE TITLE
Port FxCop rule CA1824: MarkAssembliesWithNeutralResourcesLanguage

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#473]
**Title:** Mark assemblies with NeutralResourcesLanguageAttribute

**Description:**

The NeutralResourcesLanguage attribute informs the ResourceManager of the language that was used to display the resources of a neutral culture for an assembly. This improves lookup performance for the first resource that you load and can reduce your working set.

**Dependency:** None

**Notes:**

**Comment by heejaechang** [comment]
@srivatsn I was thinking adding fixer for this rule and decide not to since
1. most of time the diagnostic is location-less diagnostic meaning until we implement codefix from error list, LB doesn't work.
2. in rare case where the attribute exist but has wrong argument such as "" or null, we don't know what locale to put into it. current locale? always english? and etc.

**Comment by heejaechang** [comment]
should I leave it open for fixer or should I close it?

**Comment by srivatsn** [comment]
Makes sense. I'll close the issue..
