### ISSUE TITLE
CA1419 is too restrictive on the ctor required

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#5231]
### Analyzer

**Diagnostic ID**: [CA1419](https://github.com/dotnet/roslyn-analyzers/pull/5043): `Provide a public parameterless constructor for concrete types derived from 'System.Runtime.InteropServices.SafeHandle`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 6 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

### Describe the bug

CA1419 is requiring that SafeHandles have a `public` parameterless ctor.  This is too restrictive.  Most custom SafeHandles are themselves `internal` to a project, so requiring it have a `public` ctor is prohibitive; to satisfy the purpose of the rule (to be usable with a source generator that needs to be able to construct the SafeHandle), the ctor need only be as visible as the type itself, e.g. internal if internal, etc.

### Steps To Reproduce

Derive an internal type from SafeHandle and add an internal parameterless ctor.

### Expected behavior

No warning.

### Actual behavior

CA1419 fires.

cc: @jkoritzinsky

**Comment by jkoritzinsky** [comment]
The only improvement we could do here is in the internal or `private protected` case. If the type is nested-protected, nested-private, or nested-protected-or-internal, we need to make the constructor public so it's visible in the enclosing type.

And since a public constructor in an internal or nested-protected-and-internal (`private protected`) type has the same effective visibility as an internal constructor in a type with these visibilities, I don't see much reason to handle these two cases specially. Especially since if the user changes the visibility of the type, they'd just get the analyzer to fire again.

**Comment by stephentoub** [comment]
> I don't see much reason to handle these two cases specially

Because otherwise the rule is firing false positives, calling out things that it claims are bugs and that then require the user to either make a stylistic change in order to shut up the warning or take the time and effort and real estate to suppress the warning.

We should fix this.

**Comment by jkoritzinsky** [comment]
That's reasonable. Fixing this for the `internal` and `private protected` cases makes sense.

**Comment by mavasani** [comment]
Fixed in 6.0.1xx branch.
