### ISSUE TITLE
Port FxCop rule CA2210: AssembliesShouldHaveValidStrongNames

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#532]
**Title:** Assemblies should have valid strong names

**Description:**

The strong name protects clients from unknowingly loading an assembly that has been tampered with. Assemblies without strong names should not be deployed outside very limited scenarios. If you share or distribute assemblies that are not correctly signed, the assembly can be tampered with, the common language runtime might not load the assembly, or the user might have to disable verification on his or her computer.

**Dependency:** None

**Notes:**

Implement the check to just see if it has a public key.

**Comment by srivatsn** [comment]
This rule was removed from FxCop as well. See #616

**Comment by srivatsn** [comment]
The rule wasn't removed from FxCop and ships in VS and needs to be reimplemented.

**Comment by heejaechang** [comment]
anyone knows how to verify signing? I know one way that uses win API but I guess we need other way to do it?

**Comment by srivatsn** [comment]
We’ve updated the guidance on [msdn](https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx) to say strong naming only gives you unique identity and that one shouldn't rely on strong names for security. Given that this rule is far less useful now. It's also historically something that's had very high noise since it fires on delay-signed assemblies as well. So there's not much point in re-implementing this rule at this point.
