### ISSUE TITLE
Port FxCop rule CA2222: DoNotDecreaseInheritedMemberVisibility

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#539]
**Title:** Do not decrease inherited member visibility

**Description:**

You should not change the access modifier for inherited members. Changing an inherited member to private does not prevent callers from accessing the base class implementation of the method.

**Dependency:** None

**Notes:**

**Comment by mjrousos** [comment]
I can take this one (though it seems I'm not able to assign the issue to myself).

**Comment by lgolding** [comment]
I will assign myself to prevent others from taking it.

**Comment by lgolding** [comment]
Assigned to me but @mjrousos will do the work.

**Comment by mjrousos** [comment]
Thanks, @lgolding !

**Comment by lgolding** [comment]
Hi @mjrousos, any word on this? I'll be happy to take it if you can't get to it.

**Comment by mjrousos** [comment]
Hi @lgolding. Sorry for the slow progress here. I got the analyzer written fairly quickly but got pulled off onto other work before I could finish a code fix or unit tests. I should be able to get to those over the next couple weeks, though if you'd like to help out that's fine by me. I'm out of the office today, but can push my changes so far to my fork of the repo so that you can see my progress.

**Comment by lgolding** [comment]
Hi @mjrousos thanks for the work so far! One option is for you to push to your fork, add me as a contributor to your fork, and I can add the unit tests and the fixer. Up to you!

**Comment by mjrousos** [comment]
@lgolding, I've pushed all my changes so far [here](https://github.com/mjrousos/roslyn-analyzers). So far, I've implemented the analyzer and added a simple positive and negative test case. Work still to be done includes:
* Adding a code fix
* Adding more test cases

I should have time to finish this the week after next, but if you want to pick it up in the meantime, that would be great. I'll make you a contributor in that repo. Just take a look at the last two commits to see the changes I've made so far.

Also, I had to fiddle around with strong name signing to get the tests passing, but I didn't commit those changes since it seems like something that may be fixed centrally or that was specific to my machine setup.

**Comment by lgolding** [comment]
Thank you @mjrousos. If you think you will have time to complete the work in a couple of weeks, I would prefer that, because I have an analyzer of my own that I keep not having the time to get around to working on. :-)

**Comment by mjrousos** [comment]
No problem

**Comment by srivatsn** [comment]
PR for this rule - https://github.com/dotnet/roslyn-analyzers/pull/828

**Comment by lgolding** [comment]
I added the Needs-Fixer label because I thought I remembered there was still work to do on that. But I looked back at the comments in the PR #828, and what it actually says is that if, in future, we modify the analyzer to fire on the property in the case where the accessors do not explicitly specify a visibility, then we should modify the fixer to highlight the property instead of the accessors. As the analyzer stands today, the fixer is correct, so there's nothing more to do. So I removed the Needs-Fixer label again.

**Comment by gewarren** [comment]
@mavasani This one, CA2222, looks like it was ported, but I don't see it here: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md

**Comment by mavasani** [comment]
@gewarren - CA2222 was ported but then removed, details in: https://github.com/dotnet/roslyn-analyzers/issues/1378. We should mark it as deprecated with justification from that issue (already covered by existing compiler diagnostic(s).

I will change the label on this issue as well.
