### ISSUE TITLE
CA1822 should have api_surface configuration

### ISSUE THREAD

**Issue by shuebner** [dotnet/roslyn-analyzers#5664]
### Analyzer

**Diagnostic ID**: [CA1822 ](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822 )

### Describe the improvement

CA1822 should be configurable to exclude public and internal members.

### Describe suggestions on how to achieve the rule

Offer configuration of the API surface via `api_surface`.

**Comment by shuebner** [comment]
It is not documented on the rule (see linke in the description) and also setting `dotnet_diagnostic.CA1822.api_surce = private` has no effect on warning reports.

**Comment by mavasani** [comment]
@shuebner However, you raise a good point, which @gewarren, @Youssef1313 and @Evangelink have also raised in the past. We should probably support both `dotnet_diagnostic.` prefix and `dotnet_code_quality.` prefix for specifying editorconfig options for CA rules (latter for backwards compatibility). Many customers have got confused due to different prefix for CA rule options. It's likely a very simple fix to the below method to add this support: https://github.com/dotnet/roslyn-analyzers/blob/186404d87db29c9a9cff55708289ae94ab5acaae/src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs#L47-L63

**Comment by shuebner** [comment]
@mavasani 
Wow, classic RTFM. How could I not have seen the documentation...?
Sorry for stealing your time.

**Comment by Evangelink** [comment]
@shuebner I have created a different issue to track supporting both prefixes.

I am closing this one, feel free to ping if there was still something unsolved.
