### ISSUE TITLE
CA1062 (validate non null) when using new !! syntax

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn-analyzers#5922]
### Analyzer

**Diagnostic ID**: CA1062

### Analyzer source

```xml
<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="7.0.0-preview1.22116.1" PrivateAssets="All" />
```

### Describe the bug

When using `<LangVersion>preview</LangVersion>`, VS suggests using `!!` to validate arguments as not null.

After applying this code fix, CA1062 appears. It doesn't seem to understand the `!!` syntax.

### Steps To Reproduce

```c#
public class C
{
    public void M(object o)
    {
        if (o is null) throw new ArgumentNullException(nameof(o));
        _ = o.ToString();
    }
}
```

Invoke codefix for IDE0190 (simplify null check), producing:

```c#
public class C
{
    public void M(object o!!)
    {
        _ = o.ToString();
        //  ^^ Invalid CA1062 here given here
    }
}
```

### Expected behavior

No diagnostic.

### Actual behavior

Diagnostic.

**Comment by Youssef1313** [comment]
Not sure about the fix since DFA is a bit complex, but probably it's to tweak the `maybeNull` argument here:

https://github.com/dotnet/roslyn-analyzers/blob/086d1cc888ca0d8c96b94444935f488fcaf3fe98/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs#L277

Very likely it's needed to add an extension method to find `ExclamationExclamation` token in `Lightup` layer. Since this is language specific and `Lightup` doesn't yet have a language-specific project, this will need to take some changes from https://github.com/dotnet/roslyn-analyzers/pull/5880 (if the PR wasn't yet merged at the time of fixing this issue)

**Comment by Youssef1313** [comment]
null-parameter checking (`!!`) feature was cancelled. The issue can be closed.
