### ISSUE TITLE
Disable CA1305 for Guid.Parse

### ISSUE THREAD

**Issue by bfren** [dotnet/roslyn-analyzers#5988]
### Analyzer

**Diagnostic ID**: [CA1305](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305): `Specify IFormatProvider`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 6 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.202](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug

Incorrect warning when using `Guid.Parse(string)`, and instruction to use an overload that does not exist: `Guid.Parse(string, IFormatProvider)`.

### Steps To Reproduce

1. Use `Guid.Parse(string)`
2. Build project with analysers

### Expected behavior

No warning

### Actual behavior

> Warning CA1305: The behavior of 'Guid.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'xxx' with a call to 'Guid.Parse(string, IFormatProvider)'.

## Additional context

An example can be found [here](https://github.com/bfren/jeebs/actions/runs/2257472954).

**Comment by bgrainger** [comment]
> instruction to use an overload that does not exist: Guid.Parse(string, IFormatProvider).

That's not strictly true; this overload was added in .NET 7. However, it simply delegates to `Guid.Parse(string)`: https://github.com/dotnet/runtime/blob/af2a48ddaec9a3e27002b0d3b80c07431c2e38c1/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L1490

The warning is still spurious because the existing code is correct and the suggested change is unnecessary. Changing code to use the `IFormatProvider` overload (a) does nothing useful, and (b) requires `#if NET7_0_OR_GREATER` blocks if multitargeting.

**Comment by svick** [comment]
I think this should be closed as a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5999 (since that one has more details about the issue).

**Comment by bfren** [comment]
Agreed - glad someone has picked this up.
