### ISSUE TITLE
Do not raise CA1416 for enumeration types

### ISSUE THREAD

**Issue by N-Olbert** [dotnet/roslyn-analyzers#5992]
### Analyzer

**Diagnostic ID**: [CA1416](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)

### Describe the improvement

Enums are stupid sets of named constants. They cannot be "platform specific" by itself. Therefore raising a CA1416 seems wrong for such types.

For example, we have used the System.Diagnostics.EventLogEntryType-enum all around in our code base to specify the logging category within our custom logging framework. During the migration to NET 6, we have made this logging framework platform independent. Since it is part of our public API we have kept the System.Diagnostics.EventLogEntryType-enum during the migrations. Now our code compiles and executes fine, but we get thousands of CA1416-errors.

I know that it is basically our fault since we have not encapsulated the framework types properly in the past, but since we can't control this for 3rd-party assemblies which made the same mistake I think you can also argue about the sense of a CA1416 for enums in general (@buyaa-n: what do you think?).

### Describe suggestions on how to achieve the rule

I suggest that this analyzer generally does not raise for enums. As beeing said enums are just named numeric values and can't have any special, potential platform specific behavior by itself.
Anyways, opting out manually would also be an option. In this case I suggest adding a new editor config option or a  MSBuild property.

**Comment by buyaa-n** [comment]
I believe there is an Enums used specifically for platform specific operations., therefore we could not exclude them all.

Is the [System.Diagnostics.EventLog](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.EventLog/Directory.Build.props#L4) is windows only, if an assembly has an `OSPlatform` attribute by design it applies to all members within the assembly, so there could be many members that not really participate in platform specific operations not only Enums, trying to separate/annotate each of them will be very tedious and also would increase assembly size. If the main functionality of an assembly/type is platform specific its much better to annotate it entirely including all members inside it.

If you are not using anything except `System.Diagnostics.EventLogEntryType` Enum then why don't you just create a similar Enum in your project and use it?

**Comment by N-Olbert** [comment]
> I believe there is an Enums used specifically for platform specific operations., therefore we could not exclude them all.
> 
> Is the [System.Diagnostics.EventLog](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.EventLog/Directory.Build.props#L4) is windows only, if an assembly has an `OSPlatform` attribute by design it applies to all members within the assembly, so there could be many members that not really participate in platform specific operations not only Enums, trying to separate/annotate each of them will be very tedious and also would increase assembly size. If the main functionality of an assembly/type is platform specific its much better to annotate it entirely including all members inside it.
> 
> If you are not using anything except `System.Diagnostics.EventLogEntryType` Enum then why don't you just create a similar Enum in your project and use it?

Ok, I agree due to simplified separation.

In fact, it affected quite a few enums for us, but I bypassed the warning by creating a copy of the original enum in one of our assemblies. Then I applied a global using to redirect the original enum type to our custom enum type.

`global using EventLogEntryType = Namespace.EventLogEntryType;`
