### ISSUE TITLE
CA2235 Unexpected Behavior When Serializable Class Has Property of Type Generic Collection of Non-Serializable Class

### ISSUE THREAD

**Issue by InbalZim** [dotnet/roslyn-analyzers#6025]
### Analyzer

[CA2235](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2235): `Mark all non-serializable fields`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.5](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

This rule doesn't raise an error in regards to generic collections.

### Steps To Reproduce

1. Create the following classes:

    - `public class Inner
{
    public string? Property1 { get; set; }
}`
    - `[Serializable]
public class Outer
{
    public List<Inner>? Collection1 { get; set; }
}`

2. Build

### Expected behavior

The following CA2235 error:
Field **Collection1** is a member of type **Outer** which is serializable but is of type **Inner** which is not serializable

### Actual behavior

No such error arises.

## Additional context

I believe this behavior applies to every type of generic collection (i.e., **Collection1** can be of any type of generic collection)

**Comment by Evangelink** [comment]
Hi @InbalZim, I have been investigating the issue and it turns out that we are bailing out on .netcore because the serializable info is no longer available for runtime types. See this line of code https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SerializationRulesDiagnosticAnalyzer.cs#L228-L233 and this comment: https://github.com/dotnet/roslyn-analyzers/issues/1775#issuecomment-519686818.

Could you confirm you are targeting .net core?

Given everything described in the linked thread, I don't think there will be any effort to try to make something better here as we are missing some info from runtime and that this is only relevant in the case of binary serialization which is obsolete.
