### ISSUE TITLE
Fix IDE0190 and IDE0200 from targeting net7.0

### ISSUE THREAD

**Issue by lbussell** [dotnet/roslyn-analyzers#6128]
### Analyzer

N/A

### Analyzer source

N/A

### Describe the bug

When targeting net7.0, roslyn-analyzers has a few new style violations:

src\Utilities\Compiler\WordParser.cs(104,29): error IDE0190: (NETCORE_ENGINEERING_TELEMETRY=Build) Null check can be simplified
src\Utilities\Compiler\PooledObjects\PooledDictionary.cs(95,65): error IDE0200: (NETCORE_ENGINEERING_TELEMETRY=Build) Lambda expression can be removed
src\Utilities\Compiler\PooledObjects\PooledConcurrentDictionary.cs(67,65): error IDE0200: (NETCORE_ENGINEERING_TELEMETRY=Build) Lambda expression can be removed
src\Utilities\Compiler\PooledObjects\PooledSortedSet.cs(64,62): error IDE0200: (NETCORE_ENGINEERING_TELEMETRY=Build) Lambda expression can be removed

### Steps To Reproduce

N/A

### Additional context

Please see https://github.com/dotnet/roslyn-analyzers/pull/6088

**Comment by Youssef1313** [comment]
This can be closed.

- With https://github.com/dotnet/roslyn-analyzers/pull/6117, we now consume a CodeStyle package that doesn't have IDE0190 ([it was removed](https://github.com/dotnet/roslyn/blob/f22d054ddb7047c67e6ae943d306443a5b20dafd/src/Analyzers/Core/Analyzers/IDEDiagnosticIds.cs#L170))
- IDE0200 was fixed in https://github.com/dotnet/roslyn-analyzers/pull/6117
