### ISSUE TITLE
Bug: `IFormatProviderOptionalRule` diagnostics aren't created with argument

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#6217]
https://github.com/dotnet/roslyn-analyzers/blob/efa7fe73a6a46ab60b95d0e36b5460cbedab5200/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs#L48-L56

https://github.com/dotnet/roslyn-analyzers/blob/efa7fe73a6a46ab60b95d0e36b5460cbedab5200/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs#L230

https://github.com/dotnet/roslyn-analyzers/blob/efa7fe73a6a46ab60b95d0e36b5460cbedab5200/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx#L1948-L1950

The `{0}` placeholder isn't replaced because no argument is passed when creating the diagnostic.

![image](https://user-images.githubusercontent.com/31348972/197275772-2ce91681-ac1c-441c-9a16-8e67e24fae7e.png)

**Comment by hwoodiwiss** [comment]
I've opened a PR to fix this

**Comment by johnkattenhorn** [comment]
Hi @hwoodiwiss, @mavasani 

I have a project which I've inherited which won't compile due to this issue; I thought that the analyzer were automatically updated post .NET5 ? I'm using Visual Studio 2022 latest build (not preview) - should this fix be included in what I have? 

Do I need to do something to my environment or the project to pick up this fix?

**Comment by hwoodiwiss** [comment]
Hey @johnkattenhorn, does the project have a global.json file? It could be that that's pinning the sdk version to one without the fix for this. 

I'm guessing your build blocker will be that [TreatWarningsAsErrors](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#treatwarningsaserrors) or similar enabled on the project. You might need to either:
- Update the global.json sdk version
- Add in in-file suppression for the warning that's blocking your build
- Add `<NoWarn>$(NoWarn);CA1305</NoWarn>` in your .csproj

If none of these work, your build issue may not be related to this.

**Comment by johnkattenhorn** [comment]
Thanks for the prompt @hwoodiwiss - I forgot the `global.json` SDK version - doh!

Apologies!
