### ISSUE TITLE
[Suggestion/Question] Break Microsoft.CodeAnalysis.Analyzers.csproj into smaller projects?

### ISSUE THREAD

**Issue by psxvoid** [dotnet/roslyn-analyzers#6434]
Hi,

Because the code analysers code-base grows, the package `Microsoft.CodeAnalysis.NetAnalyzers` grows larger and larger (probably others too). It works great, BUT. I do not have the most powerful PC (it's not the slowest either). I tried to implement a .NET analyzer last year, but It's hard to run, debug and test those analyzers due to slow IDE performance. Because every time I type a symbol, dotnet analyzers slow my IDE (I tried VS 2019, Rider and VS Code), and the analyzer process freezes the IDE for 3-5 seconds.

Probably, it does not affect everyone. Probably, I can turn off the analyzers temporarily, or create a separate project containing only my analyzer and then cherry-pick commits. But I'm wondering, is it time to break `Microsoft.CodeAnalysis.NetAnalyzers` into smaller projects?

My laptop's info:
|||
|-|-|
|Processor	| Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz |
|Installed RAM	| 16.0 GB (15.8 GB usable) |
|System type	| 64-bit operating system, x64-based processor |

P.S. I believe that this project is one of the most important projects in .NET infrastructure. Thank for the awesome work!

**Comment by Youssef1313** [comment]
It's likely that there is/are specific analyzer(s) that are slow for your case (especially dataflow ones).

Some of the known slow analyzers: https://github.com/dotnet/roslyn-analyzers/issues/6412 https://github.com/dotnet/roslyn-analyzers/issues/4914

Breaking the project won't help. At the end, we want to ship a single NuGet package.

Even if multiple NuGet packages are considered, that is not really the fix for the slowness you are seeing. The appropriate fix is to understand which analyzer(s) is/are specifically slow, and fix them, or suppress them if you don't want them, or enforce them only in CI for better performance of local development.

As a starting point, a binary log of a slow build with `<ReportAnalyzer>true</ReportAnalyzer>` would be good to know the slow analyzer. Performance traces might help too.

**Comment by Youssef1313** [comment]
and regarding package size, I'll look into reducing the package size. 7.0.0 is currently 4MB, which I agree could be improved, and already planning to reduce it. see https://github.com/dotnet/roslyn-analyzers/issues/6422

**Comment by mavasani** [comment]
I am going to close out this issue as the original suggestion is not relevant. Please file issues for any performance bottlenecks that you observe, and if possible, please provide performance traces for them as suggested by @Youssef1313.
