### ISSUE TITLE
Globalization Rules in Query Expression

### ISSUE THREAD

**Issue by dahlbyk** [dotnet/roslyn-analyzers#6743]
### Analyzer

**Diagnostic ID**: [Globalization rules](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/globalization-warnings), e.g. [CA1304](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1304), [CA1307](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1307), [CA1310](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1310), [CA1311](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1311)

### Describe the improvement

EF doesn't support `StringComparison` overloads, for good reason: https://github.com/dotnet/efcore/issues/1222. So while CA1307 and friends are generally useful, they're never correct inside an EF query expression. We'd prefer not to disable the diagnostics globally, so we end up with a lot of `#pragma` around queries.

Suggest either:

- Don't check some/all globalization rules within expressions.
- Split out separate diagnostics IDs for globalization rules within expressions.

**Comment by roji** [comment]
StringComparison may not work specifically for EF, but there are other expression contexts where it does. In fact, even with EF, some values of StringComparison (case sensitive/insensitive) do work when using the Cosmos provider - things really depend on exactly which database provider is being used.

So I don't think it's appropriate to do a sweeping disabling (or even distinction) based on whether something happens within an expression or not.

The long-term solution here is probably for EF to have its own diagnostics suppressor, and for that suppressor to be made aware of which database provider is being used (probably explicitly by the user via an .editorconfig setting, since having a suppressor detect the EF provider is probably unfeasible). At that point, we could suppress diagnostics within expressions based on that.

**Comment by dahlbyk** [comment]
@roji appreciate your input. I guess I missed that an Analyzer can suppress other diagnostics (https://github.com/dotnet/roslyn/issues/20242), so the compiler already had what we need to fix this.
