### ISSUE TITLE
PublicApiAnalyzers awareness of ExperimentalAttribute annotations

### ISSUE THREAD

**Issue by RussKie** [dotnet/roslyn-analyzers#6759]
The compiler has added the support for `System.Diagnostics.CodeAnalysis.ExperimentalAttribute` in https://github.com/dotnet/roslyn/pull/68702. The design is here: https://github.com/dotnet/designs/blob/main/accepted/2023/preview-apis/preview-apis.md.

It would be great to make PublicApiAnalyzers aware of the attribute. I've no idea what it would entail, starting this as a discussion.

Here are things that came to mind:

1. Annotation of the experimental API in "PublicApi.Shipped/Unshipped.txt". 
I suppose, an API could be prefixed with "[experimental]", e.g.:
    ```
    [experimental]Microsoft.Extensions.ExtraAnalyzers.UsingToStringInLoggersAnalyzer
    [experimental]Microsoft.Extensions.ExtraAnalyzers.UsingToStringInLoggersAnalyzer.UsingToStringInLoggersAnalyzer() -> void
    [experimental]override Microsoft.Extensions.ExtraAnalyzers.AsyncCallInsideUsingBlockAnalyzer.Initialize(Microsoft.CodeAnalysis.Diagnostics.AnalysisContext! context) -> void
    ```

2. An experimental API can be removed from a shipped package, so it'd be acceptable for an API recorded as an experimental to be removed from PublicApi.Shipped.txt.

3. An experimental API can be "graduated" to become a stable API, so the annotation in PublicApi.Shipped.txt and PublicApi.Unshipped.txt  can change.
    ```diff
    -  [experimental]Microsoft.Extensions.ExtraAnalyzers.UsingToStringInLoggersAnalyzer
    +  Microsoft.Extensions.ExtraAnalyzers.UsingToStringInLoggersAnalyzer
    -  [experimental]Microsoft.Extensions.ExtraAnalyzers.UsingToStringInLoggersAnalyzer.UsingToStringInLoggersAnalyzer() -> void
    +  Microsoft.Extensions.ExtraAnalyzers.UsingToStringInLoggersAnalyzer.UsingToStringInLoggersAnalyzer() -> void
    -  [experimental]override Microsoft.Extensions.ExtraAnalyzers.AsyncCallInsideUsingBlockAnalyzer.Initialize(Microsoft.CodeAnalysis.Diagnostics.AnalysisContext! context) -> void
    +  override Microsoft.Extensions.ExtraAnalyzers.AsyncCallInsideUsingBlockAnalyzer.Initialize(Microsoft.CodeAnalysis.Diagnostics.AnalysisContext! context) -> void
    ```

4. A shipped stable API can't become an experimental.
(proposed by @rafal-mz in https://github.com/dotnet/roslyn-analyzers/issues/6759#issuecomment-1632016611)

6. An experimental API should not be allowed to leak through a stable API
    ```cs
    public class StableApi
    {
       public class ExperimentalApi ProblemApi {get; set;} // Warning: experimental API leaks through stable API.

       [Experimental]
       public class ExperimentalApi OkApi {get; set;} // No warning
    }

    [Experimental]
    public class ExperimentalApi
    {
    }
    ```
    (proposed by @rafal-mz in https://github.com/dotnet/roslyn-analyzers/issues/6759#issuecomment-1632016611)

**Comment by RussKie** [comment]
@geeknoid @rafal-mz do you have anything to add?

**Comment by rafal-mz** [comment]
- Stable/Obsolete APIs cannot go back in time and become Experimental again. This should be one-way process.
- Ideally, normal APIs should not be able to expose experimental APIs through they API surface. E.g.

```
public class Nlormal
{
   public class Experimental E {get ;set;}
   ^^^^^^^^^^^^^^^^^^^^^^^ <- experimental API leaks through stable API.
}

[Experimental]
public class Experimental
{
}
```

- Developer should not be able to create API as stable. All new APIs should be enforced to be experimental before they stabilize.
- I don't remember if it is the case for ApiAnalyzers today, but they should prevent from removing interfaces from classes. E.g. 'myClass : IMyClass' should break if we remove 'IMyClass' implementation.

I think these are all requirements. I think we don't support 2 in our internal tool as of today, so it is kind of 'would be nice to have it'.

**Comment by RussKie** [comment]
> * Developer should not be able to create API as stable. All new APIs should be enforced to be experimental before they stabilize.

Could you please elaborate on how you see this enforced through the analyzer? 
I suppose this could be an opt-in rule, but this feels like a niche use-case (at least at this stage) better achieved through a business process. 

I am having troubles seeing a material benefit from this rule for the majority of the existing .NET projects out there, but this is my personal opinion.

**Comment by RussKie** [comment]
@mavasani @sharwell @Youssef1313 it would be great to have your take on this proposal.

**Comment by rafal-mz** [comment]
We were creating an SDK, and we couldn't afford to break existing customers. At the same time, features demand was much higher than dotnet repos since we were releasing once a month. We couldn't release feature as stable, and then refactor it a month later. You cannot imagine how many customers came angry to us. They had to re-invest in implementing our SDK month-after-month as they didn't know that what we did was not ready.

At the other hand, we wanted each library to be tested by partner that requested it, gather feedback and then stabilize API. This is how 'ExperimentalAttribute', and 3 stage api lifecycle proposition appeared. We've created a few analyzers

- one that flag experimental features in the same way as compiler flags obsolete features,
- one that enforces our developers to include a template in obsolete attribute message that indicates what is the replacement for a given obsolete API.
- one that understands api lifecycles and has ~5-6 diagnostics to support it.

Yes, we needed a process, and it seemed natural to build it inside our development environment. Analyzer that just encodes what needs to be done is much better than 3 pages of docs. Especially if you have around ~60 people contributing and asking the same questions over and over.

Is it niche? I don't think so. It is just different environment than other .NET projects that we have. I think it is OK because we could evolve and innovate at must faster pace. There are other languages like Rust that use 3 phase API lifecycle as well.

> Could you please elaborate on how you see this enforced through the analyzer?

The analyzer we've built was also based on files. Instead of reading .txt with custom format, we've stored api related data as .json. Then, at runtime the analyzer was recognizing the json file that lays next to the assembly, and read the api stage from it and other metadata.

During the monthly releases, we were updating json files with current .dll snapshot. It effectively mean, that our json file held snapshot of latest-released version, and runtime was reacting to observed changes in the API based on that.

**Comment by jcouv** [comment]
I think it makes sense to record the `[experimental]` portion in the publicAPI files (part 1 of the proposal). 
But I would shy away from trying to enforce any policies around it (parts 2, 3, and 4). I'd leave that up to code reviewers, as we do today.
As for the last part (part 5, preventing non-experimental APIs from leaking experimental types), I would recommend a dedicated analyzer. Also I don't think this can be completely secured: imagine adding a experimental derived type, which could be leaked by an API that returns the non-experimental base type...
