### ISSUE TITLE
Microsoft.CodeAnalysis.ResxSourceGenerator missing `Format` methods sporadically

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-analyzers#6889]
### Analyzer

Microsoft.CodeAnalysis.ResxSourceGenerator

### Problem

The Microsoft.CodeAnalysis.ResxSourceGenerator generator sometimes 'forgets' to generate the Format* methods for resource strings that need it. This manifests as occasional error list entries claiming a Format method call doesn't bind, all while full builds succeed.
![image](https://github.com/dotnet/roslyn-analyzers/assets/3548/df34cc38-42b3-4c72-b2e9-6ec17c4da79d)
I've seen this problem several times, across projects.

This is with v3.3.5-beta1.23330.2 of the source generator, and VS 17.7.1.

**Comment by sharwell** [comment]
This is almost certainly caused by having a mismatch in the version of the various analyzer packages produced by this repository. They each include a copy of the AddAllResxFilesAsAdditionalFiles target, but some older versions of this target failed to include properties for resx that are read by ResxSourceGenerator. Can you make sure all of the analyzers are updated to 3.11.0-beta1.23503.1 / 9.0.0-preview.23503.1 or newer?

**Comment by AArnott** [comment]
@sharwell, I did what I could to unify the roslyn analyzer versions in https://github.com/nerdcash/Nerdbank.Cryptocurrencies/pull/99/files.
But the error list errors remain.

**Comment by AArnott** [comment]
Fixed. Thanks.
