### ISSUE TITLE
Test and product assemblies are signed with different keys

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#739]
The stub generation tool specified different keys for the product (analyzer) assemblies and the unit test assemblies. As a result, you can't debug unit tests in VS because you get a strong name key error. The workaround until this is fixed is:

1. Right-click the unit test project, and then select **Properties**.
2. Select the **Signing** tab.
3. Uncheck **Sign the assembly**.
4. Do the same for the corresponding product (analyzers) assembly.

**DO NOT CHECK IN THOSE CHANGES!!!***

**Comment by genlu** [comment]
@lgolding This was inherited from the target file pre-refactoring, which seems to be intentional. Maybe @srivatsn and @tmeschter can provide more info?

https://github.com/dotnet/roslyn-analyzers/blob/master/build/Targets/Analyzers.Imports.targets#L61

**Comment by lgolding** [comment]
@srivatsn @tmeschter Any thoughts on this?

**Comment by tmeschter** [comment]
Roslyn has always used different keys for product and test assemblies. The product binaries need to be signed with an official MS key, and getting them fully signed is a lengthy process. Test assemblies do not need the official key, so we use a checked-in key specific to Roslyn. 

The end result is that on developer boxes the test assemblies will be fully signed, but the product assemblies will be delay signed and then "fake" signed, where we just flip the "this assembly is fully signed" bit without actually fully signing it. Usually, the CLR just looks at that bit without verification, and everything just works.

However, test runners that setup separate app domains for running tests may turn on full verification, in which case the runtime will reject the fake-signed assemblies. When I originally setup the roslyn-analyzers repo this was the case for the xUnit VS test runner, and it's use was explicitly not supported. The only supported way of debugging tests is to set the unit test project as the startup project, and run with F5. This will launch the xUnit console runner, configured to *not* use separate app domains.

It is possible the underlying issue has been fixed in the xUnit VS test runner, in which case someone just needs to do the work of moving us to a newer version of xUnit. But otherwise the problem you're experiencing is expected.

Note that the point of fake signing is to avoid workarounds like the one described above, and they are strongly discouraged.

**Comment by lgolding** [comment]
Thanks @tmeschter. I will try your F5 approach, and I'll also try upgrading to the latest Xunit, and then I'll close this issue with one or the other of those resolutions.

**Comment by lgolding** [comment]
I installed the latest xunit.runner.visualstudio (2.1.0) into the project Microsoft.ApiDesignGuidelines.Analyzers.UnitTests, did Run All in the Test Explorer, and got all 1025 test failing with the "strong name signature not verified" error. So it's not fixed in latest Xunit.

Setting the unit test project as the startup project and pressing F5 works as Tom described. So I will close this issue.
