### ISSUE TITLE
Make the analyzer that warns about ISymbol derivations warn about IOperation as well.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#863]
#### Analyzer package

Microsoft.CodeAnalysis.Analyzers

#### Analyzer

DoNotDerviceFromISymbol

Extend this analyzer to warn about IOperation as well.

**Comment by bkoelman** [comment]
An analyzer with that name does not exist. The closest I could find is https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Core/InternalImplementationOnlyAnalyzer.cs.

I have tried to add a test next to https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Test/InternalImplementationOnlyTests.cs#L177, but it fails because [IOperation](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/IOperation.cs) does not have the `[InternalImplementationOnly]` marker like [ISymbol](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Symbols/ISymbol.cs) does.

```csharp
        [Fact]
        public void CSharp_VerifyIOperation()
        {
            var source = @"
public class Foo : Microsoft.CodeAnalysis.IOperation { }
public class Bar : Microsoft.CodeAnalysis.Semantics.IInvocationExpression { }
";
            DiagnosticResult[] expected = new[] { GetCSharpExpectedDiagnostic(2, 14, "Foo", "IOperation"), GetBasicExpectedDiagnostic(5, 14, "Bar", "IInvocationExpression") };

            // Verify that IOperation is not implementable.
            VerifyCSharp(source, addLanguageSpecificCodeAnalysisReference: true, expected: expected);
        }
```

Is there any reason why the marker is missing on `IOperation`?

**Comment by bkoelman** [comment]
Please reopen this issue. We should add the unittest above, once the roslyn bits are available.

**Comment by bkoelman** [comment]
@nguerrera can you please reopen?

**Comment by nguerrera** [comment]
I don't understand how I closed it.

**Comment by bkoelman** [comment]
Me neither :)

**Comment by nguerrera** [comment]
Lol. It seems pushing a commit to any repo in GitHub with 'fix org/repo#NNN' will close the issue in another repo. I expect this will get closed a lot as folks take dotnet/roslyn@701404c in to their forks. :(

**Comment by mavasani** [comment]
We should probably just file another issue to track this :)

**Comment by bkoelman** [comment]
I was thinking the same, just created https://github.com/dotnet/roslyn-analyzers/issues/999.

**Comment by srivatsn** [comment]
Closing this issue since the remaining work is tracked by #999
