### ISSUE TITLE
BasicRemoveUnusedLocalsAnalyzer CA1804 false report for local used in linq expression

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#935]
#### Repro steps
1. Open Analyzers.sln
2. Change Dependencies\CodeAnalysis\project.json to include: `"Microsoft.CodeAnalysis.FxCopAnalyzers": "1.2.0-beta1"`
3. Restore NuGet packages for solution
4. Open Desktop.Analyzers\VisualBasic\Helpers\SyntaxNodeHelper.vb, line 212

![falsereportca1804](https://cloud.githubusercontent.com/assets/10605811/14577598/d36e5d78-032a-11e6-8487-d1d6f58bf6ef.png)

Seems like an IOperation bug (analyzer is just looking for all ILocalReferenceExpression), but someone should confirm before porting it to Roslyn repo. @basoundr can you confirm as you originally wrote this analyzer?

@JohnHamby @genlu  do you know if this is fixed in latest bits of Roslyn?

**Comment by JohnHamby** [comment]
This is an IOperation bug. Linq expression are presently not property represented. The local reference is not seen by the analyzer. In the days before we used the IOperation walker to find all operations, the reference would have been reported, but we now depend on a correct representation in order to find child nodes. (That the Linq expression is not represented now causes the operands to the Linq expression to disappear.)

This will be fixed before IOperation ships for real (by representing Linq expression properly.)

**Comment by basoundr** [comment]
@mavasani yes, I wrote that rule

**Comment by mavasani** [comment]
Please remove all the suppressions for this warning ID in Analyzers.sln (not yet checked in) once this is fixed.

**Comment by mavasani** [comment]
Assigning this to @333fred as well. This should be fixed with 2.3.0 Roslyn bits, and the work here is removing all the in-source suppressions for CA1804 once we move to newer packages.

**Comment by 333fred** [comment]
Fixed with #1248.
